# Generated by Django 4.2.4 on 2023-08-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('publisherid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BookPublisher',
            },
        ),
        migrations.CreateModel(
            name='GameDevelopers',
            fields=[
                ('developerid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GameDevelopers',
            },
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('platformid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GamePlatform',
            },
        ),
        migrations.CreateModel(
            name='GamePublisher',
            fields=[
                ('publisherid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GamePublisher',
            },
        ),
        migrations.CreateModel(
            name='Lokalita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název lokality')),
                ('popis', models.TextField(verbose_name='Popis lokality')),
                ('adresa', models.CharField(max_length=255, verbose_name='Adresa lokality')),
            ],
            options={
                'verbose_name': 'Lokalita',
                'verbose_name_plural': 'Lokality',
                'db_table': 'Lokalita',
            },
        ),
        migrations.CreateModel(
            name='MetaCountry',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'MetaCountry',
            },
        ),
        migrations.CreateModel(
            name='MetaGenre',
            fields=[
                ('genreid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'MetaGenre',
            },
        ),
        migrations.CreateModel(
            name='MetaWorld',
            fields=[
                ('worldid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'MetaWorld',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('titleCZ', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=128)),
                ('oldurl', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField()),
                ('releaseyear', models.DateField()),
                ('duration', models.IntegerField()),
                ('language', models.CharField(max_length=5)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('world', models.ForeignKey(db_column='WorldID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaworld')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ratingid', models.IntegerField()),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metacountry')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.gamedevelopers')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metagenre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.gameplatform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.gamepublisher')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metaworld')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metacountry')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metagenre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.bookpublisher')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.metaworld')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
