# Generated by Django 4.2.4 on 2023-10-14 18:51

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('dateofbirth', models.DateField(db_column='DateOfBirth')),
                ('gender', models.CharField(db_column='Gender', max_length=6)),
                ('city', models.CharField(db_column='City', max_length=255)),
                ('signupdate', models.DateField(db_column='SignUpDate')),
                ('lastlogin', models.DateField(db_column='LastLogin')),
                ('isactive', models.IntegerField(db_column='IsActive')),
                ('isadmin', models.IntegerField(db_column='IsAdmin')),
                ('profilepicture', models.CharField(db_column='ProfilePicture', max_length=255)),
                ('bio', models.TextField(db_column='Bio')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='URL', max_length=255)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('h1', models.CharField(db_column='H1', max_length=255)),
                ('h2', models.CharField(db_column='H2', max_length=255)),
                ('tagline', models.CharField(db_column='Tagline', max_length=64)),
                ('content', models.TextField(db_column='Content')),
                ('youtube', models.CharField(blank=True, db_column='Youtube', max_length=20, null=True)),
                ('img1600', models.CharField(db_column='Img1600', max_length=255)),
                ('img500x500', models.CharField(db_column='Img500x500', max_length=255)),
                ('img400x250', models.CharField(db_column='Img400x250', max_length=255)),
                ('alt', models.CharField(db_column='Alt', max_length=255)),
                ('perex', models.CharField(db_column='Perex', max_length=255)),
                ('autor', models.CharField(db_column='Autor', max_length=255)),
                ('typ', models.CharField(db_column='Typ', max_length=50)),
                ('counter', models.IntegerField(db_column='Counter')),
                ('created', models.DateField(db_column='Created')),
                ('updated', models.DateField(db_column='Updated')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(db_column='BookID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('author', models.CharField(db_column='Author', max_length=255)),
                ('googleid', models.CharField(db_column='GoogleID', max_length=16, null=True)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Bookcover',
            fields=[
                ('coverid', models.IntegerField(db_column='CoverID', primary_key=True, serialize=False)),
                ('bookid', models.IntegerField(db_column='BookID')),
                ('cover', models.CharField(db_column='Cover', max_length=255)),
            ],
            options={
                'db_table': 'BookCover',
            },
        ),
        migrations.CreateModel(
            name='Bookpublisher',
            fields=[
                ('publisherid', models.IntegerField(db_column='PublisherID', primary_key=True, serialize=False)),
                ('publishername', models.CharField(db_column='PublisherName', max_length=255)),
            ],
            options={
                'db_table': 'BookPublisher',
            },
        ),
        migrations.CreateModel(
            name='Charactermeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterid', models.IntegerField(db_column='CharacterID')),
                ('charactername', models.CharField(db_column='CharacterName', max_length=255)),
                ('characterdescription', models.TextField(blank=True, db_column='CharacterDescription', null=True)),
            ],
            options={
                'db_table': 'CharacterMeta',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creatorid', models.IntegerField(db_column='CreatorID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=512, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('deathdate', models.DateField(blank=True, db_column='DeathDate', null=True)),
                ('imdbid', models.CharField(db_column='Imdb_id', max_length=16, null=True)),
                ('popularity', models.CharField(db_column='Popularity', max_length=32, null=True)),
                ('img', models.CharField(db_column='IMG', max_length=32, null=True)),
                ('knownfordepartment', models.CharField(db_column='KnownForDepartment', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Creator',
            },
        ),
        migrations.CreateModel(
            name='Creatorrole',
            fields=[
                ('roleid', models.IntegerField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=255)),
                ('rolenamecz', models.CharField(blank=True, db_column='RoleNameCZ', max_length=255)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=255)),
            ],
            options={
                'db_table': 'CreatorRole',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drinkid', models.IntegerField(db_column='DrinkID', primary_key=True, serialize=False)),
                ('drinkname', models.CharField(db_column='DrinkName', max_length=255)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Drink',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.IntegerField(db_column='FoodID', primary_key=True, serialize=False)),
                ('foodname', models.CharField(db_column='FoodName', max_length=255)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(db_column='GameID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('ratingid', models.IntegerField(db_column='RatingID')),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
        migrations.CreateModel(
            name='Gamedevelopers',
            fields=[
                ('developerid', models.IntegerField(db_column='DeveloperID', primary_key=True, serialize=False)),
                ('developername', models.CharField(db_column='DeveloperName', max_length=255)),
            ],
            options={
                'db_table': 'GameDevelopers',
            },
        ),
        migrations.CreateModel(
            name='Gameplatform',
            fields=[
                ('platformid', models.IntegerField(db_column='PlatformID', primary_key=True, serialize=False)),
                ('platform', models.CharField(db_column='Platform', max_length=255)),
                ('url', models.CharField(blank=True, db_column='PlatformURL', max_length=255)),
            ],
            options={
                'db_table': 'GamePlatform',
            },
        ),
        migrations.CreateModel(
            name='Gamepublisher',
            fields=[
                ('publisherid', models.IntegerField(db_column='PublisherID', primary_key=True, serialize=False)),
                ('publishername', models.CharField(db_column='PublisherName', max_length=255)),
            ],
            options={
                'db_table': 'GamePublisher',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.IntegerField(db_column='ItemID', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='ItemName', max_length=255, unique=True)),
                ('itemname_cz', models.CharField(blank=True, db_column='ItemNameCZ', max_length=255)),
                ('itemdescription', models.TextField(db_column='ItemDescription')),
                ('itemtype', models.CharField(blank=True, choices=[('1', 'Zbraň'), ('2', 'Nástroj'), ('3', 'Oděv'), ('4', 'Vozidlo'), ('5', 'Dokument'), ('6', 'Klenot'), ('7', 'Domácí potřeby'), ('8', 'Magický předmět'), ('9', 'Artefakt'), ('10', 'Ostatní')], db_column='ItemType', max_length=3, null=True)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(db_column='LocationID', primary_key=True, serialize=False)),
                ('locationname', models.CharField(db_column='LocationName', max_length=255, unique=True)),
                ('locationtype', models.CharField(db_column='LocationType', max_length=50)),
                ('locationdescription', models.TextField(db_column='LocationDescription')),
                ('parentlocationid', models.IntegerField(blank=True, db_column='ParentLocationID', null=True)),
                ('locationadress', models.CharField(blank=True, db_column='LocationAdress', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Metacollection',
            fields=[
                ('collectionid', models.IntegerField(db_column='CollectionID', primary_key=True, serialize=False)),
                ('collectionname', models.CharField(db_column='CollectionName', max_length=255)),
                ('collectiondescription', models.TextField(db_column='CollectionDescription')),
            ],
            options={
                'db_table': 'MetaCollection',
            },
        ),
        migrations.CreateModel(
            name='Metacountry',
            fields=[
                ('countryid', models.IntegerField(db_column='CountryID', primary_key=True, serialize=False)),
                ('countryname', models.CharField(db_column='CountryName', max_length=255)),
                ('countrycode', models.CharField(db_column='CountryCode', max_length=4)),
                ('countrycode2', models.CharField(blank=True, db_column='CountryCode2', max_length=2)),
                ('countrynamecz', models.CharField(db_column='CountryNameCZ', max_length=255)),
            ],
            options={
                'db_table': 'MetaCountry',
            },
        ),
        migrations.CreateModel(
            name='Metagenre',
            fields=[
                ('genreid', models.IntegerField(db_column='GenreID', primary_key=True, serialize=False)),
                ('genrename', models.CharField(db_column='GenreName', max_length=255)),
                ('genrenamecz', models.CharField(db_column='GenreNameCZ', max_length=255)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True, unique=True)),
                ('tmdbid', models.IntegerField(db_column='TmdbID')),
            ],
            options={
                'db_table': 'MetaGenre',
            },
        ),
        migrations.CreateModel(
            name='Metaworld',
            fields=[
                ('worldid', models.IntegerField(db_column='WorldID', primary_key=True, serialize=False)),
                ('worldname', models.CharField(db_column='WorldName', max_length=255)),
                ('worlddescription', models.TextField(db_column='WorldDescription', null=True)),
            ],
            options={
                'db_table': 'MetaWorld',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.IntegerField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('titlecz', models.CharField(db_column='TitleCZ', default='', max_length=255)),
                ('special', models.IntegerField(blank=True, choices=[('1', 'Top'), ('2', 'CZ')], db_column='Special', null=True)),
                ('url', models.CharField(db_column='URL', max_length=255, unique=True)),
                ('oldurl', models.CharField(db_column='OldURL', max_length=255, null=True)),
                ('img', models.CharField(db_column='IMG', default='/static/img/filmy/nomovie.jpg', max_length=255)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('releaseyear', models.CharField(db_column='ReleaseYear', max_length=4, null=True)),
                ('duration', models.IntegerField(db_column='Duration', null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=5, null=True)),
                ('budget', models.IntegerField(db_column='Budget', null=True)),
                ('adult', models.IntegerField(db_column='Adult', default='0')),
                ('popularity', models.CharField(db_column='Popularity', max_length=6, null=True)),
                ('idcsfd', models.CharField(db_column='ID_Csfd', max_length=16, null=True)),
                ('idimdb', models.CharField(db_column='ID_Imdb', max_length=16, null=True)),
                ('iddiv', models.CharField(db_column='ID_DIV', max_length=16, null=True)),
                ('worldid', models.ForeignKey(blank=True, db_column='WorldID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld')),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Tvshow',
            fields=[
                ('tvshowid', models.IntegerField(db_column='TVShowID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('premieredate', models.DateField(db_column='PremiereDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('rating', models.IntegerField(db_column='Rating')),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
            ],
            options={
                'db_table': 'TVShow',
            },
        ),
        migrations.CreateModel(
            name='Tvseason',
            fields=[
                ('sessionid', models.IntegerField(db_column='SessionID', primary_key=True, serialize=False)),
                ('seasonnumber', models.IntegerField(db_column='SeasonNumber')),
                ('premieredate', models.DateField(db_column='PremiereDate')),
                ('enddate', models.DateField(db_column='EndDate')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVSeason',
            },
        ),
        migrations.CreateModel(
            name='Tvepisode',
            fields=[
                ('episodeid', models.IntegerField(db_column='EpisodeID', primary_key=True, serialize=False)),
                ('episodenumber', models.IntegerField(db_column='EpisodeNumber')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('airdate', models.DateField(db_column='AirDate')),
                ('description', models.TextField(db_column='Description')),
                ('sessionid', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvseason')),
            ],
            options={
                'db_table': 'TVEpisode',
            },
        ),
        migrations.CreateModel(
            name='Movieversions',
            fields=[
                ('movieversionid', models.IntegerField(db_column='MovieVersionID', primary_key=True, serialize=False)),
                ('versionname', models.CharField(db_column='VersionName', max_length=255)),
                ('duration', models.IntegerField(db_column='Duration')),
                ('releasedate', models.DateField(db_column='ReleaseDate')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieVersions',
            },
        ),
        migrations.CreateModel(
            name='Movierating',
            fields=[
                ('ratingid', models.IntegerField(db_column='RatingID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(db_column='Comment')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovieRating',
            },
        ),
        migrations.CreateModel(
            name='Moviegenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieGenre',
            },
        ),
        migrations.CreateModel(
            name='Moviecrew',
            fields=[
                ('moviecrewid', models.AutoField(db_column='MovieCrewID', primary_key=True, serialize=False, unique=True)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('peopleid', models.ForeignKey(db_column='PeopleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'MovieCrew',
            },
        ),
        migrations.CreateModel(
            name='Moviecountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieCountries',
            },
        ),
        migrations.CreateModel(
            name='Moviecomments',
            fields=[
                ('commentid', models.IntegerField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovieComments',
            },
        ),
        migrations.CreateModel(
            name='Metacity',
            fields=[
                ('cityid', models.IntegerField(db_column='CityID', primary_key=True, serialize=False)),
                ('namecity', models.CharField(db_column='NameCity', max_length=255)),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
            ],
            options={
                'db_table': 'MetaCity',
            },
        ),
        migrations.CreateModel(
            name='Locationmovie',
            fields=[
                ('movielocationid', models.IntegerField(db_column='MovieLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('locationid', models.ForeignKey(db_column='LocationID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.location')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'LocationMovie',
            },
        ),
        migrations.CreateModel(
            name='Locationgame',
            fields=[
                ('gamelocationid', models.IntegerField(db_column='GameLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('locationid', models.ForeignKey(db_column='LocationID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.location')),
            ],
            options={
                'db_table': 'LocationGame',
            },
        ),
        migrations.CreateModel(
            name='Locationbook',
            fields=[
                ('booklocationid', models.IntegerField(db_column='BookLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('locationid', models.ForeignKey(db_column='LocationID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.location')),
            ],
            options={
                'db_table': 'LocationBook',
            },
        ),
        migrations.CreateModel(
            name='Itemmovie',
            fields=[
                ('movieitemid', models.IntegerField(db_column='MovieItemID', primary_key=True, serialize=False)),
                ('itemrole', models.IntegerField(db_column='ItemRole')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'ItemMovie',
            },
        ),
        migrations.CreateModel(
            name='Itemmedia',
            fields=[
                ('mediaitemid', models.AutoField(db_column='MediaItemID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(choices=[('1', 'Book'), ('2', 'Game'), ('3', 'Movie')], db_column='MediaType')),
                ('role', models.IntegerField(choices=[('1', 'Main'), ('2', 'Side'), ('3', 'Prop')], db_column='Role')),
                ('mediaid', models.IntegerField(db_column='MediaID')),
                ('item', models.ForeignKey(db_column='Item', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemMedia',
            },
        ),
        migrations.CreateModel(
            name='Itemgame',
            fields=[
                ('gameitemid', models.IntegerField(db_column='GameItemID', primary_key=True, serialize=False)),
                ('itemrole', models.CharField(db_column='ItemRole', max_length=255)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemGame',
            },
        ),
        migrations.CreateModel(
            name='Itembook',
            fields=[
                ('bookitemid', models.IntegerField(db_column='BookItemID', primary_key=True, serialize=False)),
                ('itemrole', models.CharField(db_column='ItemRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemBook',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='locationid',
            field=models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.location'),
        ),
        migrations.CreateModel(
            name='Gamerating',
            fields=[
                ('ratingid', models.IntegerField(db_column='RatingID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(db_column='Comment')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GameRating',
            },
        ),
        migrations.CreateModel(
            name='Gamepurchase',
            fields=[
                ('purchaseid', models.IntegerField(db_column='PurchaseID', primary_key=True, serialize=False)),
                ('purchasedate', models.DateField(db_column='PurchaseDate')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GamePurchase',
            },
        ),
        migrations.CreateModel(
            name='Gamecomments',
            fields=[
                ('commentid', models.IntegerField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GameComments',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AddField(
            model_name='game',
            name='developerid',
            field=models.ForeignKey(db_column='DeveloperID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamedevelopers'),
        ),
        migrations.AddField(
            model_name='game',
            name='genreid',
            field=models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platformid',
            field=models.ForeignKey(db_column='PlatformID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gameplatform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisherid',
            field=models.ForeignKey(db_column='PublisherID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamepublisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='worldid',
            field=models.ForeignKey(db_column='WorldID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
        migrations.CreateModel(
            name='Foodmedia',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(db_column='MediaType')),
                ('foodid', models.ForeignKey(db_column='FoodID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.food')),
            ],
            options={
                'db_table': 'FoodMedia',
            },
        ),
        migrations.CreateModel(
            name='Drinkmedia',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(db_column='MediaType')),
                ('drinkid', models.ForeignKey(db_column='DrinkID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.drink')),
            ],
            options={
                'db_table': 'DrinkMedia',
            },
        ),
        migrations.CreateModel(
            name='Creatorintvshow',
            fields=[
                ('creatorintvshowid', models.IntegerField(db_column='CreatorInTVShowID', primary_key=True, serialize=False)),
                ('creatorid', models.ForeignKey(db_column='CreatorID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'CreatorInTVShow',
            },
        ),
        migrations.CreateModel(
            name='Creatorinmovie',
            fields=[
                ('creatorinmovieid', models.IntegerField(db_column='CreatorInMovieID', primary_key=True, serialize=False)),
                ('creatorid', models.ForeignKey(db_column='CreatorID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'CreatorInMovie',
            },
        ),
        migrations.CreateModel(
            name='Creatoringame',
            fields=[
                ('creatoringameid', models.IntegerField(db_column='CreatorInGameID', primary_key=True, serialize=False)),
                ('creatorid', models.ForeignKey(db_column='CreatorID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'CreatorInGame',
            },
        ),
        migrations.CreateModel(
            name='CreatorBiography',
            fields=[
                ('biographyid', models.AutoField(primary_key=True, serialize=False)),
                ('biographytext', models.TextField(blank=True, db_column='BiographyText')),
                ('source', models.CharField(blank=True, db_column='Source', max_length=255)),
                ('lastupdated', models.DateField(auto_now=True, db_column='LastUpdated')),
                ('language', models.CharField(db_column='Language', default='en', max_length=10)),
                ('shortdescription', models.TextField(blank=True, db_column='ShortDescription')),
                ('externallink', models.URLField(blank=True, db_column='ExternalLink')),
                ('imageurl', models.URLField(blank=True, db_column='ImageURL')),
                ('notes', models.TextField(blank=True, db_column='Notes')),
                ('author', models.CharField(blank=True, db_column='Author', max_length=255)),
                ('verificationstatus', models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified'), ('Pending', 'Pending')], db_column='VerificationStatus', default='Unverified', max_length=10)),
                ('is_primary', models.BooleanField(db_column='IsPrimary', default=False)),
                ('creator', models.ForeignKey(db_column='CreatorID', on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='div_content.creator')),
                ('userid', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CreatorBiography',
            },
        ),
        migrations.AddField(
            model_name='creator',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.IntegerField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('comment_date', models.DateField(db_column='CommentDate')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Charactertvshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvshowcharacterid', models.IntegerField(db_column='TVShowCharacterID')),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'CharacterTVShow',
            },
        ),
        migrations.CreateModel(
            name='Charactermovie',
            fields=[
                ('moviecharacterid', models.AutoField(db_column='MovieCharacterID', primary_key=True, serialize=False)),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'CharacterMovie',
            },
        ),
        migrations.CreateModel(
            name='Charactergame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamecharacterid', models.IntegerField(db_column='GameCharacterID')),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'CharacterGame',
            },
        ),
        migrations.CreateModel(
            name='Characterbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcharacterid', models.IntegerField(db_column='BookCharacterID')),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
            ],
            options={
                'db_table': 'CharacterBook',
            },
        ),
        migrations.CreateModel(
            name='Bookrating',
            fields=[
                ('ratingid', models.IntegerField(db_column='RatingID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(db_column='Comment')),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BookRating',
            },
        ),
        migrations.CreateModel(
            name='Bookpurchase',
            fields=[
                ('purchaseid', models.IntegerField(db_column='PurchaseID', primary_key=True, serialize=False)),
                ('purchasedate', models.DateField(db_column='PurchaseDate')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BookPurchase',
            },
        ),
        migrations.CreateModel(
            name='Bookisbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('edition', models.CharField(blank=True, max_length=255, null=True)),
                ('publicationyear', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverimage', models.URLField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbns', to='div_content.book')),
            ],
            options={
                'db_table': 'BookISBN',
            },
        ),
        migrations.CreateModel(
            name='Bookcomments',
            fields=[
                ('commentid', models.IntegerField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BookComments',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AddField(
            model_name='book',
            name='genreid',
            field=models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisherid',
            field=models.ForeignKey(db_column='PublisherID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.bookpublisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='worldid',
            field=models.ForeignKey(db_column='WorldID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
        migrations.AddField(
            model_name='user',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
