# Generated by Django 4.2.4 on 2023-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacountry',
            name='countrycode',
            field=models.CharField(db_column='CountryCode', max_length=4),
        ),
    ]
