# Generated by Django 4.2.4 on 2023-09-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('h1', models.CharField(max_length=255)),
                ('h2', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('img1600', models.ImageField(upload_to='art/1600/')),
                ('img500x500', models.ImageField(upload_to='art/500x500/')),
                ('img400x250', models.ImageField(upload_to='art/400x250/')),
                ('alt', models.CharField(max_length=255, unique=True)),
                ('perex', models.TextField()),
                ('article', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('typ', models.CharField(max_length=50)),
                ('counter', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titleCZ',
            new_name='titlecz',
        ),
        migrations.AddField(
            model_name='gameplatform',
            name='platform',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
