# Generated by Django 4.2.4 on 2024-07-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauniversum',
            name='universumcounter',
            field=models.CharField(blank=True, db_column='UniversumCounter', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='metauniversum',
            name='universumimg',
            field=models.CharField(blank=True, db_column='UniversumIMG', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='metauniversum',
            name='universumimgposter',
            field=models.CharField(blank=True, db_column='UniversumIMGposter', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='metauniversum',
            name='universumurl',
            field=models.CharField(blank=True, db_column='UniversumURL', max_length=255, null=True),
        ),
    ]
