# Generated by Django 4.2.4 on 2023-10-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0002_alter_bookcomments_userid_alter_bookpurchase_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorbiography',
            name='biographytext',
            field=models.TextField(blank=True, db_column='BiographyText', null=True),
        ),
    ]
