# Generated by Django 4.2.4 on 2023-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0002_alter_metacountry_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(blank=True, db_column='Budget', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=5, null=True),
        ),
    ]
