# Generated by Django 4.2.4 on 2023-10-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0003_alter_creatorbiography_biographytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='bookpurchase',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='bookrating',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='creatorbiography',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='gamecomments',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='gamepurchase',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='gamerating',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='moviecomments',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='movierating',
            name='userid',
        ),
    ]
