# Generated by Django 4.2.4 on 2023-09-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0003_alter_movie_budget_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='worldid',
            field=models.ForeignKey(blank=True, db_column='WorldID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
    ]
