# Generated by Django 4.2.4 on 2023-09-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0004_alter_movie_worldid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id_csfd',
            field=models.IntegerField(db_column='ID_Csfd', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id_imdb',
            field=models.IntegerField(db_column='ID_Imdb', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id_tmdb',
            field=models.IntegerField(db_column='ID_Tmdb', null=True),
        ),
    ]
