# Generated by Django 4.2.4 on 2024-07-20 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0004_alter_movie_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movielinks',
            fields=[
                ('linkid', models.AutoField(db_column='LinkID', primary_key=True, serialize=False, unique=True)),
                ('link', models.TextField(db_column='Link', max_length=255, unique=True)),
                ('linkType', models.CharField(db_column='LinkType', max_length=255)),
                ('date_added', models.DateField(auto_now_add=True, db_column='DateAdded')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovieLinks',
            },
        ),
    ]
