# Generated by Django 4.2.4 on 2023-10-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0004_remove_bookcomments_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metagenre',
            name='tmdbid',
            field=models.IntegerField(blank=True, db_column='TmdbID', null=True),
        ),
    ]
