# Generated by Django 4.2.4 on 2023-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0004_alter_movie_releaseyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
