# Generated by Django 4.2.4 on 2023-09-03 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0005_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world',
            field=models.ForeignKey(db_column='WorldID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.metaworld'),
        ),
    ]
