# Generated by Django 4.2.4 on 2024-07-20 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0005_movielinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielinks',
            name='user',
        ),
        migrations.AddField(
            model_name='movielinks',
            name='linkDescription',
            field=models.CharField(blank=True, db_column='LinkDescription', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movielinks',
            name='linktext',
            field=models.CharField(blank=True, db_column='LinkText', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movielinks',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='link',
            field=models.CharField(db_column='Link', max_length=255, unique=True),
        ),
    ]
