# Generated by Django 4.2.4 on 2023-10-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
