# Generated by Django 4.2.4 on 2024-07-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0006_remove_movielinks_user_movielinks_linkdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielinks',
            old_name='linkDescription',
            new_name='linkdescription',
        ),
    ]
