# Generated by Django 4.2.4 on 2023-09-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0006_bookisbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metacollection',
            fields=[
                ('collectionid', models.IntegerField(db_column='CollectionID', primary_key=True, serialize=False)),
                ('collectionname', models.CharField(db_column='CollectionName', max_length=255)),
                ('collectionDescription', models.TextField(db_column='CollectionDescription')),
            ],
            options={
                'db_table': 'MetaCollection',
            },
        ),
        migrations.RemoveField(
            model_name='metaworld',
            name='worlddescrtiption',
        ),
        migrations.AddField(
            model_name='metaworld',
            name='worlddescription',
            field=models.TextField(db_column='WorldDescription', default=''),
        ),
    ]
