# Generated by Django 4.2.4 on 2024-07-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0007_rename_linkdescription_movielinks_linkdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielinks',
            name='linkautor',
            field=models.CharField(blank=True, db_column='LinkAuthor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='linkdescription',
            field=models.CharField(blank=True, db_column='LinkDescription', max_length=512, null=True),
        ),
    ]
