# Generated by Django 4.2.4 on 2023-09-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0007_metacollection_remove_metaworld_worlddescrtiption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(db_column='IMG', default='/static/img/filmy/nomovie.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(db_column='Budget', null=True),
        ),
    ]
