# Generated by Django 4.2.4 on 2023-10-16 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0007_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userprofileid',
            field=models.IntegerField(db_column='UserProfileID', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
