# Generated by Django 4.2.4 on 2023-10-16 13:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('div_content', '0008_remove_movierating_comment_remove_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='movierating',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='movierating',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movierating',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movierating',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='movieid',
            field=models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='ratingid',
            field=models.AutoField(db_column='RatingID', primary_key=True, serialize=False),
        ),
    ]
