# Generated by Django 4.2.4 on 2023-09-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0009_book_googleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='titlecz',
            field=models.CharField(db_column='TitleCZ', default='', max_length=255),
        ),
    ]
