# Generated by Django 4.2.4 on 2023-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0010_alter_movie_titlecz'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.IntegerField(db_column='Adult', default='0'),
        ),
    ]
