# Generated by Django 4.2.4 on 2024-07-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0010_alter_moviedistributor_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedistributor',
            old_name='description',
            new_name='distributordescription',
        ),
        migrations.RenameField(
            model_name='moviedistributor',
            old_name='name',
            new_name='distributorname',
        ),
    ]
