# Generated by Django 4.2.4 on 2024-07-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0011_rename_description_moviedistributor_distributordescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metakeywords',
            fields=[
                ('keywordid', models.AutoField(db_column='KeywordID', primary_key=True, serialize=False)),
                ('tmdbid', models.IntegerField(blank=True, db_column='TmdbID', max_length=9, null=True)),
                ('keyword', models.CharField(db_column='Keyword', max_length=255, unique=True)),
                ('keywordcz', models.CharField(blank=True, db_column='KeywordCZ', max_length=255, null=True)),
            ],
            options={
                'db_table': 'MetaKeywords',
            },
        ),
        migrations.RenameField(
            model_name='moviedistributor',
            old_name='distributordescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='moviedistributor',
            old_name='distributorname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='linkdescription',
            field=models.CharField(blank=True, db_column='LinkDescription', max_length=5125, null=True),
        ),
        migrations.CreateModel(
            name='Movieproductions',
            fields=[
                ('movieproductiondid', models.AutoField(db_column='MovieProductionID', primary_key=True, serialize=False)),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
                ('productionid', models.ForeignKey(db_column='ProductionID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movieproduction')),
            ],
            options={
                'db_table': 'MovieProductions',
                'unique_together': {('productionid', 'movieid')},
            },
        ),
        migrations.CreateModel(
            name='Moviekeywords',
            fields=[
                ('moviekeywordid', models.AutoField(db_column='MovieKeywordID', primary_key=True, serialize=False)),
                ('keywordid', models.ForeignKey(db_column='KeywordID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metakeywords')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieKeywords',
                'unique_together': {('movieid', 'keywordid')},
            },
        ),
        migrations.CreateModel(
            name='Gamekeywords',
            fields=[
                ('gamekeywordid', models.AutoField(db_column='GameKeywordID', primary_key=True, serialize=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='div_content.game')),
                ('keywordid', models.ForeignKey(db_column='KeywordID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metakeywords')),
            ],
            options={
                'db_table': 'GameKeywords',
                'unique_together': {('gameid', 'keywordid')},
            },
        ),
        migrations.CreateModel(
            name='Bookkeywords',
            fields=[
                ('bookkeywordid', models.AutoField(db_column='BookKeywordID', primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book')),
                ('keywordid', models.ForeignKey(db_column='KeywordID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metakeywords')),
            ],
            options={
                'db_table': 'BookKeywords',
                'unique_together': {('bookid', 'keywordid')},
            },
        ),
    ]
