# Generated by Django 4.2.4 on 2023-09-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0011_movie_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(db_column='Duration', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='oldurl',
            field=models.CharField(db_column='OldURL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='releaseyear',
            field=models.TextField(db_column='ReleaseYear', null=True),
        ),
    ]
