# Generated by Django 4.2.4 on 2024-07-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0012_metakeywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaproduction',
            fields=[
                ('metaproductionid', models.AutoField(db_column='MetaProductionID', primary_key=True, serialize=False)),
                ('tmdbid', models.IntegerField(blank=True, db_column='TmdbID', null=True)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('headquarters', models.CharField(blank=True, db_column='Headquarters', max_length=255, null=True)),
                ('homepage', models.URLField(blank=True, db_column='Homepage', null=True)),
                ('logopath', models.CharField(db_column='LogoPath', default='n.png', max_length=255)),
                ('origincountry', models.CharField(blank=True, db_column='OriginCountry', max_length=4, null=True)),
                ('countryid', models.ForeignKey(blank=True, db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('parentcompanyid', models.ForeignKey(blank=True, db_column='ParentCompanyID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.metaproduction')),
            ],
            options={
                'db_table': 'MetaProduction',
            },
        ),
        migrations.AlterField(
            model_name='movieproductions',
            name='productionid',
            field=models.ForeignKey(db_column='MetaProductionID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaproduction'),
        ),
        migrations.DeleteModel(
            name='Movieproduction',
        ),
    ]
