# Generated by Django 4.2.4 on 2023-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0013_alter_movie_id_csfd_alter_movie_id_imdb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaworld',
            name='worlddescription',
            field=models.TextField(db_column='WorldDescription', null=True),
        ),
    ]
