# Generated by Django 4.2.4 on 2024-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0013_metaproduction_alter_movieproductions_productionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomments',
            name='dateadded',
            field=models.DateField(auto_now=True, db_column='DateAdded'),
        ),
    ]
