# Generated by Django 4.2.4 on 2024-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0014_moviecomments_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakeywords',
            name='tmdbid',
            field=models.IntegerField(blank=True, db_column='TmdbID', null=True),
        ),
    ]
