# Generated by Django 4.2.4 on 2023-10-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0015_alter_movie_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermovie',
            name='characterid',
        ),
    ]
