# Generated by Django 4.2.4 on 2023-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0015_alter_movie_releaseyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id_tmdb',
        ),
        migrations.AddField(
            model_name='movie',
            name='id_div',
            field=models.CharField(db_column='ID_DIV', max_length=16, null=True),
        ),
    ]
