# Generated by Django 4.2.4 on 2023-10-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0016_remove_charactermovie_characterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecrew',
            name='characterid',
        ),
    ]
