# Generated by Django 4.2.4 on 2023-09-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0016_remove_movie_id_tmdb_movie_id_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.CharField(db_column='Popularity', max_length=6, null=True),
        ),
    ]
