# Generated by Django 4.2.4 on 2024-08-08 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0017_metakeywords_keywordurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlenews',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='URL', max_length=255)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('news', models.CharField(db_column='News', max_length=512)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=32, null=True)),
                ('alt', models.CharField(db_column='Alt', max_length=64)),
                ('perex', models.CharField(db_column='Perex', max_length=128)),
                ('source', models.CharField(db_column='Source', max_length=32)),
                ('typ', models.CharField(db_column='Typ', max_length=16)),
                ('counter', models.IntegerField(db_column='Counter')),
                ('created', models.DateField(auto_now_add=True, db_column='Created')),
                ('updated', models.DateField(auto_now=True, db_column='Updated')),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleNews',
            },
        ),
        migrations.CreateModel(
            name='NewsAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenttype', models.CharField(db_column='ContentType', max_length=50)),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('news', models.ForeignKey(db_column='NewsID', on_delete=django.db.models.deletion.CASCADE, to='div_content.articlenews')),
            ],
            options={
                'db_table': 'NewsAssociation',
                'unique_together': {('news', 'contenttype', 'objectid')},
            },
        ),
    ]
