# Generated by Django 4.2.4 on 2023-10-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0017_remove_moviecrew_characterid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterbook',
            name='characterid',
        ),
        migrations.RemoveField(
            model_name='charactergame',
            name='characterid',
        ),
        migrations.RemoveField(
            model_name='charactertvshow',
            name='characterid',
        ),
    ]
