# Generated by Django 4.2.4 on 2023-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0017_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='img',
            field=models.CharField(db_column='IMG', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='popularity',
            field=models.CharField(db_column='Popularity', default='0', max_length=32),
        ),
    ]
