# Generated by Django 4.2.4 on 2023-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0018_remove_characterbook_characterid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermeta',
            name='characterid',
            field=models.IntegerField(db_column='CharacterID', null=True),
        ),
    ]
