# Generated by Django 4.2.4 on 2023-09-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0018_creator_img_creator_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='deathday',
            field=models.DateField(db_column='DeathDate', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='imdb_id',
            field=models.CharField(db_column='Imdb_id', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='knownfordepartment',
            field=models.CharField(db_column='KnownForDepartment', max_length=255, null=True),
        ),
    ]
