# Generated by Django 4.2.4 on 2023-09-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0019_remove_creator_nationality_creator_deathday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='deathday',
            field=models.DateField(db_column='DeathDate', null=True),
        ),
    ]
