# Generated by Django 4.2.4 on 2024-08-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0019_rename_newsassociation_articlenewsassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='news',
            field=models.CharField(db_column='News', max_length=1024),
        ),
    ]
