# Generated by Django 4.2.4 on 2023-10-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0020_alter_characterbook_bookcharacterid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactergame',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='charactermovie',
            name='movieid',
        ),
        migrations.RemoveField(
            model_name='charactertvshow',
            name='tvshowid',
        ),
        migrations.RemoveField(
            model_name='moviecrew',
            name='movieid',
        ),
        migrations.RemoveField(
            model_name='moviecrew',
            name='peopleid',
        ),
        migrations.RemoveField(
            model_name='moviecrew',
            name='roleid',
        ),
        migrations.DeleteModel(
            name='Characterbook',
        ),
        migrations.DeleteModel(
            name='Charactergame',
        ),
        migrations.DeleteModel(
            name='Charactermovie',
        ),
        migrations.DeleteModel(
            name='Charactertvshow',
        ),
        migrations.DeleteModel(
            name='Moviecrew',
        ),
    ]
