# Generated by Django 4.2.4 on 2023-09-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0021_remove_creator_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='birthdate',
            field=models.DateField(blank=True, db_column='BirthDate', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='deathday',
            field=models.DateField(blank=True, db_column='DeathDate', null=True),
        ),
    ]
