# Generated by Django 4.2.4 on 2023-10-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0021_remove_charactergame_gameid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charactermeta',
        ),
    ]
