# Generated by Django 4.2.4 on 2024-08-09 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0021_forumsection_forumtopic_forumcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtopic',
            name='section',
        ),
        migrations.RemoveField(
            model_name='forumtopic',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forumcomment',
        ),
        migrations.DeleteModel(
            name='Forumsection',
        ),
        migrations.DeleteModel(
            name='Forumtopic',
        ),
    ]
