# Generated by Django 4.2.4 on 2023-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0022_delete_charactermeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charactermeta',
            fields=[
                ('characterid', models.AutoField(db_column='CharacterID', primary_key=True, serialize=False)),
                ('charactername', models.CharField(db_column='CharacterName', max_length=255)),
                ('characterdescription', models.TextField(blank=True, db_column='CharacterDescription', null=True)),
            ],
            options={
                'db_table': 'CharacterMeta',
            },
        ),
    ]
