# Generated by Django 4.2.4 on 2023-10-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0023_charactermeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviecrew',
            fields=[
                ('moviecrewid', models.AutoField(db_column='MovieCrewID', primary_key=True, serialize=False, unique=True)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('peopleid', models.ForeignKey(db_column='PeopleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'MovieCrew',
            },
        ),
        migrations.CreateModel(
            name='Charactertvshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvshowcharacterid', models.IntegerField(db_column='TVShowCharacterID')),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'CharacterTVShow',
            },
        ),
        migrations.CreateModel(
            name='Charactermovie',
            fields=[
                ('moviecharacterid', models.AutoField(db_column='MovieCharacterID', primary_key=True, serialize=False)),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'CharacterMovie',
            },
        ),
        migrations.CreateModel(
            name='Charactergame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamecharacterid', models.IntegerField(db_column='GameCharacterID')),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'CharacterGame',
            },
        ),
        migrations.CreateModel(
            name='Characterbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcharacterid', models.IntegerField(blank=True, db_column='BookCharacterID', null=True)),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
            ],
            options={
                'db_table': 'CharacterBook',
            },
        ),
    ]
