# Generated by Django 4.2.4 on 2023-09-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0023_remove_creator_nationality'),
    ]

