# Generated by Django 4.2.4 on 2024-08-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0024_forumsection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='topicurl',
            field=models.SlugField(db_column='URL', max_length=255, unique=True),
        ),
    ]
