# Generated by Django 4.2.4 on 2023-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0026_remove_creator_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='popularity',
            field=models.CharField(db_column='Popularity', max_length=32, null=True),
        ),
    ]
