# Generated by Django 4.2.4 on 2023-10-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0026_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userprofileid',
            field=models.AutoField(db_column='UserProfileID', primary_key=True, serialize=False),
        ),
    ]
