# Generated by Django 4.2.4 on 2023-09-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0027_remove_creator_nationality_alter_creator_popularity'),
    ]


