# Generated by Django 4.2.4 on 2024-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0027_forumsection_forumtopic_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsection',
            name='imageurl',
            field=models.URLField(blank=True, db_column='ImageURL', help_text='Image URL', null=True),
        ),
    ]
