# Generated by Django 4.2.4 on 2023-09-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0028_remove_creator_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='deathday',
            new_name='deathdate',
        ),
    ]
