# Generated by Django 4.2.4 on 2023-10-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0028_userlist_alter_userprofile_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlistmovie',
            unique_together={('userlist', 'movie')},
        ),
    ]
