# Generated by Django 4.2.4 on 2023-10-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0029_alter_userlistmovie_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAChange',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('created', models.DateField(db_column='Created')),
            ],
        ),
    ]
