# Generated by Django 5.1 on 2024-08-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0029_alter_forumsection_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='lasteditedat',
            field=models.DateTimeField(blank=True, db_column='LastEditedAt', null=True),
        ),
    ]
