# Generated by Django 4.2.4 on 2023-09-18 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0029_rename_deathday_creator_deathdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
    ]
