# Generated by Django 4.2.4 on 2023-09-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0030_remove_creator_nationality_alter_creator_countryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacountry',
            name='countrycode2',
            field=models.CharField(blank=True, db_column='CountryCode2', max_length=2),
        ),
    ]
