# Generated by Django 5.1 on 2024-08-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0030_forumcomment_lasteditedat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articleblog',
            fields=[
                ('articleblogid', models.AutoField(db_column='ArticleBlogID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('blogurl', models.CharField(db_column='BlogURL', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleBlog',
            },
        ),
        migrations.CreateModel(
            name='Articleblogpost',
            fields=[
                ('articleblogpostid', models.AutoField(db_column='ArticleBlogPostID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('blogposturl', models.CharField(db_column='BlogPostURL', max_length=255)),
                ('content', models.TextField(db_column='Content')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_column='PublishedAt')),
                ('tags', models.CharField(blank=True, db_column='Tags', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('is_public', models.BooleanField(db_column='IsPublic', default=True)),
                ('articleblog', models.ForeignKey(db_column='ArticleBlogID', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='div_content.articleblog')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleBlogPost',
            },
        ),
        migrations.CreateModel(
            name='Articleblogcomment',
            fields=[
                ('articleblogcommentid', models.AutoField(db_column='ArticleBlogCommentID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('articleblogpost', models.ForeignKey(db_column='ArticleBlogPostID', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='div_content.articleblogpost')),
            ],
            options={
                'db_table': 'ArticleBlogComment',
            },
        ),
        migrations.CreateModel(
            name='ArticleInteraction',
            fields=[
                ('articleinteractionid', models.AutoField(db_column='ArticleInteractionID', primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(db_column='InteractionType', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('articleblogpost', models.ForeignKey(db_column='ArticleBlogPostID', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='div_content.articleblogpost')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleInteraction',
            },
        ),
    ]
