# Generated by Django 4.2.4 on 2023-10-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0030_aachange'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aachange',
            table='AAChange',
        ),
    ]
