# Generated by Django 5.1 on 2024-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0031_articleblog_articleblogpost_articleblogcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblog',
            name='blogurl',
        ),
        migrations.RemoveField(
            model_name='articleblogpost',
            name='blogposturl',
        ),
        migrations.AddField(
            model_name='articleblog',
            name='slug',
            field=models.SlugField(blank=True, db_column='Slug', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='articleblogpost',
            name='slug',
            field=models.SlugField(blank=True, db_column='Slug', max_length=255, null=True, unique=True),
        ),
    ]
