# Generated by Django 4.2.4 on 2023-09-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0031_remove_creator_nationality_metacountry_countrycode2'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorrole',
            name='rolenamecz',
            field=models.CharField(blank=True, db_column='RoleNameCZ', max_length=255),
        ),
    ]
