# Generated by Django 4.2.4 on 2023-10-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0031_alter_aachange_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermeta',
            name='characterurl',
            field=models.URLField(blank=True, db_column='Characterurl', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='charactermeta',
            name='charactername',
            field=models.CharField(db_column='CharacterName', max_length=255, unique=True),
        ),
    ]
