# Generated by Django 4.2.4 on 2023-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0032_charactermeta_characterurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermeta',
            name='erurl',
            field=models.URLField(blank=True, db_column='url', max_length=255, null=True),
        ),
    ]
