# Generated by Django 5.1 on 2024-08-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0032_remove_articleblog_blogurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='blog_type',
            field=models.CharField(choices=[('book', 'Knižní'), ('game', 'Herní'), ('movie', 'Filmový'), ('general', 'Obecný')], db_column='BlogType', default='general', max_length=10),
        ),
        migrations.AlterField(
            model_name='articleblog',
            name='slug',
            field=models.SlugField(db_column='Slug', default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
