# Generated by Django 5.1 on 2024-08-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0033_articleblog_blog_type_alter_articleblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
