# Generated by Django 4.2.4 on 2023-09-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0033_remove_creator_nationality_creatorrole_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorrole',
            name='roleid',
            field=models.AutoField(db_column='RoleID', primary_key=True, serialize=False),
        ),
    ]
