# Generated by Django 4.2.4 on 2023-09-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0034_remove_creator_nationality_alter_creatorrole_roleid'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='moviecrew',
#            name='id',
#        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='moviecrewid',
            field=models.AutoField(db_column='MovieCrewID', auto_created=True,  primary_key=True, serialize=False),
        ),
    ]
