# Generated by Django 4.2.4 on 2023-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0034_remove_creator_nationality_alter_creatorrole_roleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorrole',
            name='roleid',
            field=models.IntegerField(db_column='RoleID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(db_column='URL', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='moviecrewid',
            field=models.IntegerField(db_column='MovieCrewID', primary_key=True, serialize=False, unique=True),
        ),
    ]
