# Generated by Django 4.2.4 on 2023-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0034_remove_charactermeta_erurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermeta',
            name='characterurl',
            field=models.URLField(blank=True, db_column='CharacterURL', max_length=255, null=True),
        ),
    ]
