# Generated by Django 4.2.4 on 2023-09-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0035_remove_creator_nationality_remove_moviecrew_id_and_more'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='moviecrew',
#            name='id',
#        ),
        migrations.AlterField(
            model_name='creator',
            name='nationality',
            field=models.CharField(db_column='Nationality', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='moviecrew',
            name='moviecrewid',
            field=models.IntegerField(db_column='MovieCrewID', primary_key=True, serialize=False),
        ),
    ]
