# Generated by Django 5.1 on 2024-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0035_remove_forumcomment_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
