# Generated by Django 4.2.4 on 2023-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0035_remove_article_article_remove_moviecrew_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemnamecz',
            field=models.CharField(blank=True, db_column='ItemNameCZ', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(db_column='ItemName', max_length=255, unique=True),
        ),
    ]
