# Generated by Django 4.2.4 on 2023-10-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0036_charactermeta_characternamecz'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermeta',
            name='charactercount',
            field=models.IntegerField(blank=True, db_column='CharacterCount', null=True),
        ),
    ]
