# Generated by Django 4.2.4 on 2023-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0036_remove_moviecrew_id_alter_creator_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplatform',
            name='url',
            field=models.CharField(blank=True, db_column='PlatformURL', max_length=255),
        ),
        migrations.AlterField(
            model_name='creatorrole',
            name='roleid',
            field=models.IntegerField(db_column='RoleID', primary_key=True, serialize=False),
        ),
    ]
