# Generated by Django 4.2.4 on 2023-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0036_remove_article_article_remove_creator_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='moviecrew',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='youtube',
            field=models.CharField(blank=True, db_column='Youtube', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gameplatform',
            name='url',
            field=models.CharField(blank=True, db_column='PlatformURL', max_length=255),
        ),
    ]
