# Generated by Django 5.1 on 2024-08-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0037_userlisttype_user_alter_userlisttype_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlisttype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userlisttype',
            name='user',
        ),
    ]
