# Generated by Django 4.2.4 on 2023-09-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0037_remove_moviecrew_id_gameplatform_url_and_more'),
    ]

    operations = [

    ]
