# Generated by Django 4.2.4 on 2023-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0038_creatorbiography_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, db_column='Bio', null=True),
        ),
    ]
