# Generated by Django 5.1 on 2024-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0038_alter_userlisttype_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaStats',
            fields=[
                ('metastatsid', models.AutoField(db_column='MetaStatsID', primary_key=True, serialize=False)),
                ('statname', models.CharField(db_column='StatName', max_length=255, unique=True)),
                ('tablemodel', models.CharField(blank=True, db_column='TableModel', max_length=255, null=True)),
                ('value', models.IntegerField(db_column='Value', default=0)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'MetaStats',
            },
        ),
    ]
