# Generated by Django 5.1 on 2024-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0039_metastats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCharts',
            fields=[
                ('MetaChartsID', models.AutoField(db_column='MetaChartsID', primary_key=True, serialize=False)),
                ('table_model', models.CharField(db_column='TableModel', max_length=255)),
                ('referenceid', models.IntegerField(db_column='ReferenceID')),
                ('ranking', models.IntegerField(db_column='Ranking')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('store', models.CharField(blank=True, db_column='Store', max_length=100, null=True)),
                ('time_period', models.CharField(blank=True, db_column='TimePeriod', max_length=50, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'MetaCharts',
            },
        ),
    ]
