# Generated by Django 4.2.4 on 2023-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0039_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=255, null=True),
        ),
    ]
