# Generated by Django 4.2.4 on 2023-10-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0039_rename_cover_image_bookisbn_coverimage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaItem',
            new_name='Itemmedia',
        ),
        migrations.AlterField(
            model_name='location',
            name='locationadress',
            field=models.CharField(blank=True, db_column='LocationAdress', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='itemmedia',
            table='ItemMedia',
        ),
    ]
