# Generated by Django 4.2.4 on 2023-10-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0040_rename_mediaitem_itemmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationname',
            field=models.CharField(db_column='LocationName', max_length=255, unique=True),
        ),
    ]
