# Generated by Django 4.2.4 on 2023-10-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0040_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecountries',
            unique_together={('movieid', 'countryid')},
        ),
    ]
