# Generated by Django 5.1 on 2024-08-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0040_metacharts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatarid', models.AutoField(db_column='AvatarID', primary_key=True, serialize=False)),
                ('imagepath', models.CharField(db_column='ImagePath', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, db_column='Avatar', null=True, on_delete=django.db.models.deletion.SET_NULL, to='div_content.avatar'),
        ),
    ]
