# Generated by Django 4.2.4 on 2023-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0041_alter_moviecountries_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(db_column='Bio', default=''),
        ),
    ]
