# Generated by Django 4.2.4 on 2023-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0041_alter_location_locationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='special',
            field=models.IntegerField(blank=True, choices=[('1', 'Top'), ('2', 'CZ')], db_column='Special', null=True),
        ),
    ]
