# Generated by Django 4.2.4 on 2023-10-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0042_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(db_column='Bio', default=' '),
        ),
    ]
