# Generated by Django 5.1 on 2024-08-25 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0042_bookcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='dateadded',
            field=models.DateTimeField(db_column='DateAdded', default=django.utils.timezone.now),
        ),
    ]
