# Generated by Django 5.1 on 2024-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0043_bookcomments_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomments',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, db_column='DateAdded'),
        ),
    ]
