# Generated by Django 4.2.4 on 2023-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0043_creator_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=512, null=True, unique=True),
        ),
    ]
