# Generated by Django 4.2.4 on 2023-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0044_alter_creator_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='metagenre',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True, unique=True),
        ),
    ]
