# Generated by Django 5.1 on 2024-08-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('div_content', '0045_alter_bookcomments_commentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdivcoins',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('totaldivcoins', models.DecimalField(db_column='TotalDivCoins', decimal_places=2, default=0, max_digits=10)),
                ('weeklydivcoins', models.DecimalField(db_column='WeeklyDivCoins', decimal_places=2, default=0, max_digits=10)),
                ('monthlydivcoins', models.DecimalField(db_column='MonthlyDivCoins', decimal_places=2, default=0, max_digits=10)),
                ('yearlydivcoins', models.DecimalField(db_column='YearlyDivCoins', decimal_places=2, default=0, max_digits=10)),
                ('lastupdated', models.DateTimeField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'db_table': 'UserDivCoins',
            },
        ),
    ]
