# Generated by Django 4.2.4 on 2023-11-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0045_remove_movie_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='averagerating',
            field=models.DecimalField(blank=True, db_column='AverageRating', decimal_places=3, max_digits=6, null=True),
        ),
    ]
