# Generated by Django 5.1 on 2024-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0046_userdivcoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdivcoins',
            name='lastupdated',
            field=models.DateField(auto_now=True, db_column='LastUpdated'),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='monthlydivcoins',
            field=models.IntegerField(db_column='MonthlyDivCoins', default=0),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='totaldivcoins',
            field=models.IntegerField(db_column='TotalDivCoins', default=0),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='weeklydivcoins',
            field=models.IntegerField(db_column='WeeklyDivCoins', default=0),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='yearlydivcoins',
            field=models.IntegerField(db_column='YearlyDivCoins', default=0),
        ),
    ]
