# Generated by Django 4.2.4 on 2023-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0046_movie_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='titleCZ',
            field=models.CharField(blank=True, db_column='TitleCZ', max_length=255),
        ),
    ]
