# Generated by Django 5.1 on 2024-08-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0047_alter_userdivcoins_lastupdated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdivcoins',
            name='monthlydivcoins',
            field=models.DecimalField(db_column='MonthlyDivCoins', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='totaldivcoins',
            field=models.DecimalField(db_column='TotalDivCoins', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='weeklydivcoins',
            field=models.DecimalField(db_column='WeeklyDivCoins', decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdivcoins',
            name='yearlydivcoins',
            field=models.DecimalField(db_column='YearlyDivCoins', decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
