# Generated by Django 4.2.4 on 2023-11-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0048_rename_titlecz_game_titlecz'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaworld',
            name='worldnamecz',
            field=models.CharField(blank=True, db_column='WorldNameCZ', max_length=255, null=True),
        ),
    ]
