# Generated by Django 5.1 on 2024-08-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0048_alter_userdivcoins_monthlydivcoins_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatar',
            table='Avatar',
        ),
    ]
