# Generated by Django 5.1 on 2024-08-31 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0049_alter_avatar_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquotes',
            name='pagenumber',
            field=models.IntegerField(blank=True, db_column='PageNumber', null=True),
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
