# Generated by Django 4.2.4 on 2023-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0049_metaworld_worldnamecz'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='averageratinggame',
            field=models.DecimalField(blank=True, db_column='AverageRatingGame', decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255),
        ),
    ]
