# Generated by Django 5.1 on 2024-09-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0050_bookquotes_pagenumber_bookquotes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookquotes',
            name='pagenumber',
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='chapter',
            field=models.IntegerField(blank=True, db_column='Chapter', null=True),
        ),
    ]
