# Generated by Django 4.2.4 on 2023-11-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0050_game_averageratinggame_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='countryid',
            field=models.ForeignKey(blank=True, db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, db_column='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='developerid',
            field=models.ForeignKey(blank=True, db_column='DeveloperID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamedevelopers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genreid',
            field=models.ForeignKey(blank=True, db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platformid',
            field=models.ForeignKey(blank=True, db_column='PlatformID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gameplatform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisherid',
            field=models.ForeignKey(blank=True, db_column='PublisherID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamepublisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ratingid',
            field=models.IntegerField(blank=True, db_column='RatingID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='worldid',
            field=models.ForeignKey(blank=True, db_column='WorldID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
    ]
