# Generated by Django 5.1 on 2024-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0051_remove_bookquotes_pagenumber_bookquotes_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquotes',
            name='thumbsdown',
            field=models.IntegerField(db_column='ThumbsDown', default=0),
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='thumbsup',
            field=models.IntegerField(db_column='ThumbsUp', default=0),
        ),
    ]
