# Generated by Django 4.2.4 on 2023-11-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0051_alter_game_countryid_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='countryid',
            field=models.ForeignKey(blank=True, db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developerid',
            field=models.ForeignKey(blank=True, db_column='DeveloperID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamedevelopers'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genreid',
            field=models.ForeignKey(blank=True, db_column='GenreID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platformid',
            field=models.ForeignKey(blank=True, db_column='PlatformID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gameplatform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisherid',
            field=models.ForeignKey(blank=True, db_column='PublisherID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.gamepublisher'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ratingid',
            field=models.IntegerField(blank=True, db_column='RatingID', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='titlecz',
            field=models.CharField(blank=True, db_column='TitleCZ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='worldid',
            field=models.ForeignKey(blank=True, db_column='WorldID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
    ]
