# Generated by Django 5.1 on 2024-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0052_bookquotes_thumbsdown_bookquotes_thumbsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='genre',
            field=models.IntegerField(blank=True, db_column='Genre', default=0, null=True),
        ),
    ]
