# Generated by Django 4.2.4 on 2023-12-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0052_alter_game_countryid_alter_game_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpublisher',
            name='publisherdescription',
            field=models.CharField(blank=True, db_column='PublisherDescription', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bookpublisher',
            name='publisherurl',
            field=models.CharField(blank=True, db_column='PublisherURL', max_length=255, null=True),
        ),
    ]
