# Generated by Django 4.2.4 on 2023-12-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0053_bookpublisher_publisherdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpublisher',
            name='publishername',
            field=models.CharField(db_column='PublisherName', max_length=255, unique=True),
        ),
    ]
