# Generated by Django 5.1 on 2024-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0054_remove_creator_genre_creator_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlenews',
            name='counter',
            field=models.IntegerField(db_column='Counter', default=1),
        ),
    ]
