# Generated by Django 4.2.4 on 2023-12-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0055_bookpublisher_publisherwww'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, db_column='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genreid',
            field=models.ForeignKey(db_column='GenreID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisherid',
            field=models.ForeignKey(db_column='PublisherID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.bookpublisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='worldid',
            field=models.ForeignKey(db_column='WorldID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaworld'),
        ),
        migrations.CreateModel(
            name='Bookauthor',
            fields=[
                ('authorid', models.IntegerField(db_column='AuthorID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=255)),
                ('lastname', models.CharField(db_column='LastName', max_length=255)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=512, null=True, unique=True)),
                ('birthdate', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('deathdate', models.DateField(blank=True, db_column='DeathDate', null=True)),
                ('goodreads', models.CharField(blank=True, db_column='GoodreadsID', max_length=16, null=True)),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=32, null=True)),
                ('countryid', models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
            ],
            options={
                'db_table': 'BookAuthor',
            },
        ),
    ]
