# Generated by Django 5.1 on 2024-09-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0056_favorite'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='favorite',
            table='Favorite',
        ),
    ]
