# Generated by Django 4.2.4 on 2023-12-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0056_alter_book_countryid_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisherid',
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, db_column='Subtitle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookisbn',
            name='publisherid',
            field=models.ForeignKey(db_column='PublisherID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.bookpublisher'),
        ),
    ]
