# Generated by Django 4.2.4 on 2023-12-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0057_remove_book_publisherid_book_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='description',
            field=models.TextField(blank=True, db_column='Description'),
        ),
    ]
