# Generated by Django 5.1 on 2024-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0057_alter_favorite_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='popularity',
            field=models.IntegerField(db_column='Popularity', null=True),
        ),
    ]
