# Generated by Django 5.1 on 2024-10-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0058_alter_creator_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacollection',
            name='collectionurl',
            field=models.CharField(blank=True, db_column='CollectionNameURL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metacollection',
            name='collectiondescription',
            field=models.TextField(blank=True, db_column='CollectionDescription', null=True),
        ),
    ]
