# Generated by Django 5.1 on 2024-10-12 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0059_metacollection_collectionurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaplatform',
            fields=[
                ('platformid', models.IntegerField(db_column='PlatformID', primary_key=True, serialize=False)),
                ('platform', models.CharField(db_column='Platform', max_length=255)),
                ('url', models.CharField(blank=True, db_column='PlatformURL', max_length=255)),
            ],
            options={
                'db_table': 'MetaPlatform',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, db_column='Year', null=True),
        ),
        migrations.CreateModel(
            name='Gamegenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('movieid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameGenre',
            },
        ),
    ]
