# Generated by Django 5.1 on 2024-10-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0060_metaplatform_remove_gameplatform_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplatform',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='gameplatform',
            name='url',
        ),
        migrations.AddField(
            model_name='gameplatform',
            name='gameid',
            field=models.ForeignKey(db_column='GameID', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameplatform',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='platformid',
            field=models.ForeignKey(blank=True, db_column='PlatformID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaplatform'),
        ),
        migrations.AlterField(
            model_name='gameplatform',
            name='platformid',
            field=models.ForeignKey(db_column='PlatformID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaplatform'),
        ),
        migrations.AlterField(
            model_name='metaplatform',
            name='platform',
            field=models.CharField(blank=True, db_column='Platform', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metaplatform',
            name='url',
            field=models.CharField(blank=True, db_column='PlatformURL', max_length=255, null=True),
        ),
    ]
