# Generated by Django 4.2.4 on 2023-12-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0061_remove_bookauthor_birth_year_bookauthor_birthyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=1024),
        ),
    ]
