# Generated by Django 5.1 on 2024-11-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0061_remove_gameplatform_platform_remove_gameplatform_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metaaward',
            fields=[
                ('metaawardid', models.AutoField(db_column='MetaAwardID', primary_key=True, serialize=False)),
                ('awardname', models.CharField(db_column='AwardName', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('awardtype', models.CharField(choices=[('film', 'Film'), ('book', 'Book'), ('game', 'Game')], db_column='AwardType', max_length=20)),
                ('year', models.PositiveIntegerField(db_column='Year')),
            ],
            options={
                'db_table': 'MetaAward',
                'unique_together': {('awardname', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Gameaward',
            fields=[
                ('gameawardid', models.AutoField(db_column='GameAwardID', primary_key=True, serialize=False)),
                ('winner', models.BooleanField(db_column='Winner', default=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='div_content.game')),
                ('metaawardid', models.ForeignKey(db_column='MetaAwardID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaaward')),
            ],
            options={
                'db_table': 'GameAward',
            },
        ),
        migrations.CreateModel(
            name='Bookaward',
            fields=[
                ('bookAwardid', models.AutoField(db_column='BookAwardID', primary_key=True, serialize=False)),
                ('winner', models.BooleanField(db_column='Winner', default=False)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book')),
                ('metaAwardid', models.ForeignKey(db_column='MetaAwardID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaaward')),
            ],
            options={
                'db_table': 'BookAward',
            },
        ),
        migrations.CreateModel(
            name='Movieaward',
            fields=[
                ('movieawardid', models.AutoField(db_column='MovieAwardID', primary_key=True, serialize=False)),
                ('winner', models.BooleanField(db_column='Winner', default=False)),
                ('metaAwardid', models.ForeignKey(db_column='MetaAwardID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaaward')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieAward',
            },
        ),
    ]
