# Generated by Django 4.2.4 on 2023-12-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0062_alter_bookauthor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='middlename',
            field=models.CharField(blank=True, db_column='MiddleName', max_length=255, null=True),
        ),
    ]
