# Generated by Django 5.1 on 2024-11-15 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0063_gamecomments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVCountries',
            fields=[
                ('tvcountryid', models.AutoField(db_column='TVCountrydID', primary_key=True, serialize=False)),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metacountry')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.CASCADE, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVCountries',
                'unique_together': {('tvshowid', 'countryid')},
            },
        ),
        migrations.CreateModel(
            name='TVKeywords',
            fields=[
                ('tvkeywordid', models.AutoField(db_column='TVKeywordID', primary_key=True, serialize=False)),
                ('keywordid', models.ForeignKey(db_column='KeywordID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metakeywords')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.CASCADE, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVKeywords',
                'unique_together': {('tvshowid', 'keywordid')},
            },
        ),
        migrations.CreateModel(
            name='TVProductions',
            fields=[
                ('tvproductionid', models.AutoField(db_column='TVProductionID', primary_key=True, serialize=False)),
                ('metaproductionid', models.ForeignKey(db_column='MetaProductionID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaproduction')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.CASCADE, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVProductions',
                'unique_together': {('metaproductionid', 'tvshowid')},
            },
        ),
    ]
