# Generated by Django 4.2.4 on 2023-12-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0063_bookauthor_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='birthyear',
            field=models.CharField(blank=True, db_column='BirthYear', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='deathyear',
            field=models.CharField(blank=True, db_column='DeathYear', max_length=5, null=True),
        ),
    ]
