# Generated by Django 4.2.4 on 2023-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0064_alter_bookauthor_birthyear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='authorid',
            field=models.AutoField(db_column='AuthorID', primary_key=True, serialize=False),
        ),
    ]
