# Generated by Django 5.1 on 2024-11-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0065_alter_tvcountries_tvcountryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvseason',
            old_name='seassonepisode',
            new_name='seasonepisode',
        ),
    ]
