# Generated by Django 4.2.4 on 2023-12-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0065_alter_bookauthor_authorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=1024, null=True),
        ),
    ]
