# Generated by Django 5.1 on 2024-11-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0066_rename_seassonepisode_tvseason_seasonepisode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvseason',
            unique_together={('tvshowid', 'seasonurl')},
        ),
    ]
