# Generated by Django 4.2.4 on 2023-12-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0067_alter_bookauthor_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=512, null=True),
        ),
    ]
