# Generated by Django 5.1 on 2024-11-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0068_alter_tvepisode_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlisttvshow',
            fields=[
                ('userlisttvshowid', models.AutoField(db_column='UserListTvshowID', primary_key=True, serialize=False)),
                ('addedat', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.tvshow')),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.userlist')),
            ],
            options={
                'db_table': 'UserListTvshow',
            },
        ),
    ]
