# Generated by Django 4.2.4 on 2023-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0068_alter_bookauthor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='databazeknih',
            field=models.CharField(blank=True, db_column='DatabazeKnih', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='goodreads',
            field=models.CharField(blank=True, db_column='GoodreadsID', max_length=12, null=True),
        ),
    ]
