# Generated by Django 5.1 on 2024-11-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0070_alter_userlisttvshow_userlisttvshowid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlisttvshow',
            table='UserListTVShow',
        ),
    ]
