# Generated by Django 4.2.4 on 2023-12-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0071_book_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='alias',
            field=models.CharField(blank=True, db_column='Alias', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='main',
            field=models.CharField(blank=True, db_column='Main', max_length=2, null=True),
        ),
    ]
