# Generated by Django 5.1 on 2024-11-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0071_alter_userlisttvshow_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlisttvepisode',
            fields=[
                ('userlisttvepisodeid', models.AutoField(db_column='UserListTVEpisodeID', primary_key=True, serialize=False)),
                ('addedat', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
                ('tvepisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.tvepisode')),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.userlist')),
            ],
            options={
                'db_table': 'UserListTVEpisode',
            },
        ),
        migrations.CreateModel(
            name='Userlisttvseason',
            fields=[
                ('userlisttvseasonid', models.AutoField(db_column='UserListTVSeasonID', primary_key=True, serialize=False)),
                ('addedat', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
                ('tvseason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.tvseason')),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.userlist')),
            ],
            options={
                'db_table': 'UserListTVSeason',
            },
        ),
    ]
