# Generated by Django 5.1 on 2024-11-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0072_userlisttvepisode_userlisttvseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='episodetype',
            field=models.CharField(blank=True, db_column='EpisodeType', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='runtime',
            field=models.IntegerField(blank=True, db_column='Runtime', null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='CreatorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=32, null=True),
        ),
    ]
