# Generated by Django 4.2.4 on 2023-12-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0072_bookauthor_alias_bookauthor_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookauthor',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='main',
        ),
    ]
