# Generated by Django 5.1 on 2024-11-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0073_tvepisode_episodetype_tvepisode_runtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvepisodecrew',
            fields=[
                ('tvepisodecrewid', models.AutoField(db_column='MovieCrewID', primary_key=True, serialize=False, unique=True)),
                ('characterid', models.ForeignKey(blank=True, db_column='CharacterID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('episodeid', models.ForeignKey(db_column='EpisodeID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
                ('peopleid', models.ForeignKey(db_column='PeopleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'TVEpisodeCrew',
            },
        ),
    ]
