# Generated by Django 4.2.4 on 2023-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0074_bookauthor_alias_bookauthor_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=2048, null=True),
        ),
    ]
