# Generated by Django 5.1 on 2024-11-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0074_tvepisodecrew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvepisodecrew',
            name='episodeid',
            field=models.ForeignKey(db_column='EpisodeID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvepisode'),
        ),
        migrations.AlterField(
            model_name='tvepisodecrew',
            name='tvepisodecrewid',
            field=models.AutoField(db_column='TVEpisodeCrewID', primary_key=True, serialize=False, unique=True),
        ),
    ]
