# Generated by Django 5.1 on 2024-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0075_alter_tvepisodecrew_episodeid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='popularity',
            field=models.IntegerField(db_column='Popularity', db_index=True, null=True),
        ),
    ]
