# Generated by Django 5.1 on 2024-11-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0076_alter_tvshow_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvcrew',
            name='episodecount',
            field=models.IntegerField(db_column='EpisodeCount', default=1),
            preserve_default=False,
        ),
    ]
