# Generated by Django 4.2.4 on 2023-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0077_bookauthor_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True),
        ),
    ]
