# Generated by Django 5.1 on 2024-11-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0078_remove_game_countryid_remove_game_developerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.IntegerField(db_column='GameID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('titlecz', models.CharField(blank=True, db_column='TitleCZ', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('ratingid', models.CharField(blank=True, db_column='RawgIO', max_length=255, null=True)),
                ('metacritic', models.IntegerField(blank=True, db_column='MetaCritic', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('averageratinggame', models.DecimalField(blank=True, db_column='AverageRatingGame', decimal_places=3, max_digits=6, null=True)),
                ('countryid', models.ForeignKey(blank=True, db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('universumid', models.ForeignKey(blank=True, db_column='UniversumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metauniversum')),
            ],
            options={
                'db_table': 'Game',
            },
        ),
    ]
