# Generated by Django 5.1 on 2024-11-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0079_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ratingid',
        ),
        migrations.AddField(
            model_name='game',
            name='rawgid',
            field=models.IntegerField(blank=True, db_column='RawgID', null=True),
        ),
    ]
