# Generated by Django 4.2.4 on 2023-12-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0079_alter_book_authorid_alter_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True),
        ),
    ]
