# Generated by Django 5.1 on 2024-11-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0080_remove_game_ratingid_game_rawgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameid',
            field=models.AutoField(db_column='GameID', primary_key=True, serialize=False),
        ),
    ]
