# Generated by Django 4.2.4 on 2023-12-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0081_alter_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
    ]
