# Generated by Django 5.1 on 2024-11-30 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0082_metadeveloper_metapublisher_gamecomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameaward',
            fields=[
                ('gameawardid', models.AutoField(db_column='GameAwardID', primary_key=True, serialize=False)),
                ('winner', models.BooleanField(db_column='Winner', default=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='div_content.game')),
                ('metaawardid', models.ForeignKey(db_column='MetaAwardID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metaaward')),
            ],
            options={
                'db_table': 'GameAward',
            },
        ),
        migrations.CreateModel(
            name='Gamegenre',
            fields=[
                ('gamegenreid', models.AutoField(db_column='GameGenreID', primary_key=True, serialize=False)),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('movieid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameGenre',
            },
        ),
        migrations.CreateModel(
            name='Gameplatform',
            fields=[
                ('gameplatformid', models.AutoField(db_column='GamePlatformID', primary_key=True, serialize=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('platformid', models.ForeignKey(db_column='PlatformID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metaplatform')),
            ],
            options={
                'db_table': 'GamePlatform',
            },
        ),
        migrations.CreateModel(
            name='Userlistgame',
            fields=[
                ('userlistgameid', models.AutoField(db_column='UserListGameID', primary_key=True, serialize=False)),
                ('addedat', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.game')),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.userlist')),
            ],
            options={
                'db_table': 'UserListGame',
            },
        ),
        migrations.CreateModel(
            name='Gamekeywords',
            fields=[
                ('gamekeywordid', models.AutoField(db_column='GameKeywordID', primary_key=True, serialize=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.CASCADE, to='div_content.game')),
                ('keywordid', models.ForeignKey(db_column='KeywordID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metakeywords')),
            ],
            options={
                'db_table': 'GameKeywords',
                'unique_together': {('gameid', 'keywordid')},
            },
        ),
    ]
