# Generated by Django 4.2.4 on 2024-01-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0082_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, db_column='Year', null=True),
        ),
    ]
