# Generated by Django 5.1 on 2024-11-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0083_gameaward_gamegenre_gameplatform_userlistgame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charactergame',
            fields=[
                ('gamecharacterid', models.AutoField(db_column='GameCharacterID', primary_key=True, serialize=False)),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'CharacterGame',
            },
        ),
        migrations.CreateModel(
            name='Gamedevelopers',
            fields=[
                ('gamedeveloperid', models.AutoField(db_column='GameDeveloperID', primary_key=True, serialize=False)),
                ('developerid', models.ForeignKey(db_column='DeveloperID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metadeveloper')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameDevelopers',
            },
        ),
        migrations.CreateModel(
            name='Gamepublisher',
            fields=[
                ('gamepublisherid', models.AutoField(db_column='GamePublisherID', primary_key=True, serialize=False)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('publisherid', models.ForeignKey(db_column='PublisherID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metapublisher')),
            ],
            options={
                'db_table': 'GamePublisher',
            },
        ),
        migrations.CreateModel(
            name='Itemgame',
            fields=[
                ('gameitemid', models.IntegerField(db_column='GameItemID', primary_key=True, serialize=False)),
                ('itemrole', models.CharField(db_column='ItemRole', max_length=255)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemGame',
            },
        ),
    ]
