# Generated by Django 4.2.4 on 2024-01-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0084_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(db_column='IMG', default='noimg.png', max_length=255),
        ),
    ]
