# Generated by Django 5.1 on 2024-12-01 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0085_alter_gamecomments_gamecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomments',
            name='gamecomment',
        ),
        migrations.RemoveField(
            model_name='gamecomments',
            name='gamecommentid',
        ),
        migrations.RemoveField(
            model_name='gamecomments',
            name='user',
        ),
        migrations.AddField(
            model_name='gamecomments',
            name='comment',
            field=models.TextField(blank=True, db_column='Comment', null=True),
        ),
        migrations.AddField(
            model_name='gamecomments',
            name='commentid',
            field=models.IntegerField(db_column='CommentID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Userchatsession',
            fields=[
                ('userchatsessionid', models.AutoField(db_column='UserChatSessionID', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('user1', models.ForeignKey(db_column='User1', on_delete=django.db.models.deletion.CASCADE, related_name='user1_chats', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(db_column='User2', on_delete=django.db.models.deletion.CASCADE, related_name='user2_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserChatSession',
                'unique_together': {('user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='Usermessage',
            fields=[
                ('usermessageid', models.AutoField(db_column='UserMessageID', primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, db_column='Message', default='', null=True)),
                ('sentat', models.DateTimeField(auto_now_add=True, db_column='SentAt')),
                ('isread', models.BooleanField(db_column='IsRead', default=False)),
                ('chatsession', models.ForeignKey(db_column='UserChatSession', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='div_content.userchatsession')),
                ('sender', models.ForeignKey(db_column='Sender', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserMessage',
                'ordering': ['sentat'],
            },
        ),
    ]
