# Generated by Django 4.2.4 on 2024-01-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0085_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lastupdated',
            field=models.DateField(auto_now=True, db_column='LastUpdated'),
        ),
    ]
