# Generated by Django 4.2.4 on 2024-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0086_movie_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.CharField(db_column='Popularity', db_index=True, max_length=7, null=True),
        ),
    ]
