# Generated by Django 5.1 on 2024-12-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0086_remove_gamecomments_gamecomment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvgenre',
        ),
    ]
