# Generated by Django 4.2.4 on 2024-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0087_alter_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='oldurl2',
            field=models.CharField(db_column='OldURL2', max_length=255, null=True),
        ),
    ]
