# Generated by Django 4.2.4 on 2024-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0088_movie_oldurl2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviedupliciy',
            fields=[
                ('duplicityid', models.AutoField(db_column='DuplicityID', primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(db_column='URL', max_length=255, unique=True)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('count', models.IntegerField(db_column='Count')),
                ('lastupdated', models.DateField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'db_table': 'MovieDuplicity',
            },
        ),
    ]
