# Generated by Django 5.1 on 2024-12-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0088_tvgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvepisodecrew',
        ),
    ]
