# Generated by Django 5.1 on 2024-12-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0089_delete_tvepisodecrew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlisttvseason',
            name='tvseason',
        ),
        migrations.RemoveField(
            model_name='userlisttvseason',
            name='userlist',
        ),
        migrations.RemoveField(
            model_name='userlisttvshow',
            name='tvshow',
        ),
        migrations.RemoveField(
            model_name='userlisttvshow',
            name='userlist',
        ),
        migrations.DeleteModel(
            name='Userlisttvepisode',
        ),
        migrations.DeleteModel(
            name='Userlisttvseason',
        ),
        migrations.DeleteModel(
            name='Userlisttvshow',
        ),
    ]
