# Generated by Django 5.1 on 2024-12-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0090_remove_userlisttvseason_tvseason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvepisode',
        ),
    ]
