# Generated by Django 4.2.4 on 2024-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0090_moviedupliciy_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movieduplicity',
            fields=[
                ('duplicityid', models.AutoField(db_column='DuplicityID', primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(db_column='URL', max_length=255, unique=True)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('public', models.IntegerField(db_column='Public', default=1)),
                ('duplicity', models.IntegerField(db_column='Duplicity', null=True)),
                ('lastupdated', models.DateField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'db_table': 'MovieDuplicity',
            },
        ),
        migrations.DeleteModel(
            name='Moviedupliciy',
        ),
    ]
