# Generated by Django 5.1 on 2024-12-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0091_delete_tvepisode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvseason',
        ),
    ]
