# Generated by Django 4.2.4 on 2024-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0091_movieduplicity_delete_moviedupliciy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvepisode',
            name='episodeimg',
            field=models.CharField(blank=True, db_column='EpisodeIMG', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='seassonepisode',
            field=models.IntegerField(blank=True, db_column='SeasonEpisode', null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='seassonimg',
            field=models.CharField(blank=True, db_column='SeasonIMG', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='seassonname',
            field=models.CharField(blank=True, db_column='SeasonName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='img',
            field=models.CharField(blank=True, db_column='IMG', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
    ]
