# Generated by Django 5.1 on 2024-12-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0092_delete_tvseason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tvkeywords',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tvkeywords',
            name='keywordid',
        ),
        migrations.RemoveField(
            model_name='tvkeywords',
            name='tvshowid',
        ),
        migrations.AlterUniqueTogether(
            name='tvproductions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tvproductions',
            name='metaproductionid',
        ),
        migrations.RemoveField(
            model_name='tvproductions',
            name='tvshowid',
        ),
        migrations.DeleteModel(
            name='TVCountries',
        ),
        migrations.DeleteModel(
            name='TVKeywords',
        ),
        migrations.DeleteModel(
            name='TVProductions',
        ),
    ]
