# Generated by Django 4.2.4 on 2024-04-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0093_metauniversum_remove_book_worldid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='universumid',
            field=models.ForeignKey(blank=True, db_column='UniversumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metauniversum'),
        ),
    ]
