# Generated by Django 5.1 on 2024-12-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0093_alter_tvkeywords_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charactertvshow',
        ),
    ]
