# Generated by Django 5.1 on 2024-12-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0094_delete_charactertvshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvgenre',
            name='genreid',
        ),
        migrations.RemoveField(
            model_name='tvgenre',
            name='tvshowid',
        ),
        migrations.DeleteModel(
            name='Tvcrew',
        ),
        migrations.DeleteModel(
            name='Tvgenre',
        ),
    ]
