# Generated by Django 5.1 on 2024-12-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0095_remove_tvgenre_genreid_remove_tvgenre_tvshowid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvshow',
        ),
    ]
