# Generated by Django 4.2.4 on 2024-04-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0096_tvgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='genreid',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=3, null=True),
        ),
    ]
