# Generated by Django 4.2.4 on 2024-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0097_remove_tvshow_genreid_tvshow_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseason',
            name='seassonname',
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='titlecz',
            field=models.CharField(blank=True, db_column='TitleCZ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvseason',
            name='titlecz',
            field=models.CharField(blank=True, db_column='titleCZ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='titlecz',
            field=models.CharField(blank=True, db_column='TitleCZ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=255, null=True),
        ),
    ]
