# Generated by Django 5.1 on 2024-12-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0099_tvepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charactertvshow',
            fields=[
                ('tvshowcharacterid', models.AutoField(db_column='TVShowCharacterID', primary_key=True, serialize=False)),
                ('characterrole', models.CharField(db_column='CharacterRole', max_length=255)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'CharacterTVShow',
            },
        ),
        migrations.CreateModel(
            name='Tvcrew',
            fields=[
                ('tvcrewid', models.AutoField(db_column='TVCrewID', primary_key=True, serialize=False)),
                ('episodecount', models.IntegerField(db_column='EpisodeCount')),
                ('characterid', models.ForeignKey(blank=True, db_column='CharacterID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('peopleid', models.ForeignKey(db_column='PeopleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVCrew',
            },
        ),
        migrations.CreateModel(
            name='Tvepisodecrew',
            fields=[
                ('tvepisodecrewid', models.AutoField(db_column='TVEpisodeCrewID', primary_key=True, serialize=False, unique=True)),
                ('characterid', models.ForeignKey(blank=True, db_column='CharacterID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
                ('episodeid', models.ForeignKey(db_column='EpisodeID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvepisode')),
                ('peopleid', models.ForeignKey(db_column='PeopleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creator')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.creatorrole')),
            ],
            options={
                'db_table': 'TVEpisodeCrew',
            },
        ),
        migrations.CreateModel(
            name='Tvgenre',
            fields=[
                ('tvgenreid', models.AutoField(db_column='TVGenreID', primary_key=True, serialize=False, unique=True)),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVGenre',
            },
        ),
    ]
