# Generated by Django 4.2.4 on 2024-04-05 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0099_remove_tvseason_sessionid_remove_tvseason_sessionurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvepisode',
            name='sessionid',
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='seasonid',
            field=models.ForeignKey(db_column='SeasonID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvseason'),
            preserve_default=False,
        ),
    ]
