# Generated by Django 4.2.4 on 2024-04-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0100_remove_tvepisode_sessionid_tvepisode_seasonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=4, null=True),
        ),
    ]
