# Generated by Django 4.2.4 on 2024-04-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0101_alter_tvshow_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseason',
            name='enddate',
        ),
    ]
