# Generated by Django 5.1 on 2024-12-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0101_userlisttvepisode_userlisttvseason_userlisttvshow_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moviegenre',
        ),
    ]
