# Generated by Django 4.2.4 on 2024-04-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0102_remove_tvseason_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='popularity',
            field=models.CharField(db_column='Popularity', db_index=True, max_length=7, null=True),
        ),
    ]
