# Generated by Django 5.1 on 2024-12-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0102_delete_moviegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tvgenre',
        ),
    ]
