# Generated by Django 5.1 on 2024-12-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0104_remove_movieversions_movieid_delete_moviecountries_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookgenre',
        ),
    ]
