# Generated by Django 5.1 on 2024-12-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0105_delete_bookgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamegenre',
        ),
    ]
