# Generated by Django 4.2.4 on 2024-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0105_alter_movie_titlecz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaIndex',
            fields=[
                ('indexid', models.AutoField(db_column='IndexID', primary_key=True, serialize=False)),
                ('section', models.CharField(db_column='Section', max_length=8)),
                ('item_id', models.IntegerField(db_column='ItemID')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('rank', models.IntegerField(db_column='Rank')),
                ('img', models.CharField(blank=True, db_column='IMG', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('last_updated', models.DateField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'db_table': 'MetaIndex',
            },
        ),
    ]
