# Generated by Django 4.2.4 on 2024-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0106_metaindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaindex',
            name='rank',
        ),
        migrations.AddField(
            model_name='metaindex',
            name='Popularity',
            field=models.IntegerField(db_column='Popularity', default=0),
        ),
    ]
