# Generated by Django 5.1 on 2024-12-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0106_delete_gamegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metagenre',
        ),
    ]
