# Generated by Django 5.1 on 2024-12-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0107_delete_metagenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcharacter',
            name='bookid',
        ),
        migrations.RemoveField(
            model_name='bookcharacter',
            name='characterid',
        ),
        migrations.DeleteModel(
            name='Articlenewsassociation',
        ),
        migrations.DeleteModel(
            name='Bookcharacter',
        ),
    ]
