# Generated by Django 4.2.4 on 2024-04-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0107_remove_metaindex_rank_metaindex_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaindex',
            name='Popularity',
        ),
        migrations.AddField(
            model_name='metaindex',
            name='popularity',
            field=models.CharField(db_column='Popularity', default=0, max_length=7),
        ),
    ]
