# Generated by Django 5.1 on 2024-12-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0108_remove_bookcharacter_bookid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlenewsassociation',
            fields=[
                ('articlenewsassociationd', models.AutoField(db_column='ArticleNewsAssociationID', primary_key=True, serialize=False)),
                ('contenttype', models.CharField(db_column='ContentType', max_length=50)),
                ('objectid', models.IntegerField(db_column='ObjectID')),
                ('news', models.ForeignKey(db_column='NewsID', on_delete=django.db.models.deletion.CASCADE, to='div_content.articlenews')),
            ],
            options={
                'db_table': 'ArticleNewsAssociation',
                'unique_together': {('news', 'contenttype', 'objectid')},
            },
        ),
    ]
