# Generated by Django 4.2.4 on 2024-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0109_alter_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.CharField(db_column='Popularity', db_index=True, max_length=9, null=True),
        ),
    ]
