# Generated by Django 5.1 on 2024-12-01 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0109_articlenewsassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcharacter',
            fields=[
                ('bookcharacterid', models.AutoField(db_column='BookCharacterID', primary_key=True, serialize=False)),
                ('charactermain', models.CharField(blank=True, db_column='CharacterMain', max_length=2, null=True)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.charactermeta')),
            ],
            options={
                'db_table': 'BookCharacter',
            },
        ),
    ]
