# Generated by Django 4.2.4 on 2024-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0110_alter_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaindex',
            name='popularity',
            field=models.CharField(db_column='Popularity', default=0, max_length=9),
        ),
    ]
