# Generated by Django 5.1 on 2024-12-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0110_bookcharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookcover',
        ),
    ]
