# Generated by Django 4.2.4 on 2024-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0111_alter_metaindex_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaindex',
            name='description',
            field=models.CharField(db_column='Description', max_length=255, null=True),
        ),
    ]
