# Generated by Django 5.1 on 2024-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0111_delete_bookcover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcover',
            fields=[
                ('bookcoverid', models.IntegerField(db_column='BookCoverID', primary_key=True, serialize=False)),
                ('bookid', models.IntegerField(db_column='BookID')),
                ('cover', models.CharField(db_column='Cover', max_length=255)),
            ],
            options={
                'db_table': 'BookCover',
            },
        ),
    ]
