# Generated by Django 4.2.4 on 2024-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0112_metaindex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='url2',
            field=models.CharField(blank=True, db_column='URL2', max_length=512, null=True),
        ),
    ]
