# Generated by Django 5.1 on 2024-12-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0112_bookcover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookisbn',
        ),
    ]
