# Generated by Django 4.2.4 on 2024-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0113_creator_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='lastupdated',
            field=models.DateField(auto_now=True, db_column='LastUpdated'),
        ),
    ]
