# Generated by Django 5.1 on 2024-12-01 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0113_delete_bookisbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookisbn',
            fields=[
                ('bookisbnid', models.AutoField(db_column='BookISBNID', primary_key=True, serialize=False)),
                ('isbn', models.CharField(db_column='ISBN', max_length=26, unique=True)),
                ('ISBNtype', models.CharField(blank=True, db_column='ISBNtype', max_length=255, null=True)),
                ('publicationyear', models.IntegerField(blank=True, db_column='PublicationYear', null=True)),
                ('format', models.CharField(blank=True, db_column='Format', max_length=100, null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('coverimage', models.URLField(blank=True, db_column='CoverIMG', null=True)),
                ('book', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book')),
                ('publisherid', models.ForeignKey(db_column='PublisherID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.bookpublisher')),
            ],
            options={
                'db_table': 'BookISBN',
            },
        ),
    ]
