# Generated by Django 4.2.4 on 2024-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0114_creator_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermeta',
            name='characterborn',
            field=models.CharField(db_column='CharacterBorn', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='charactermeta',
            name='characterdeath',
            field=models.CharField(db_column='CharacterDeath', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='charactermeta',
            name='characterimg',
            field=models.CharField(db_column='CharacterIMG', max_length=128, null=True),
        ),
    ]
