# Generated by Django 5.1 on 2024-12-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0114_bookisbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booklocation',
        ),
    ]
