# Generated by Django 5.1 on 2024-12-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0115_delete_booklocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklocation',
            fields=[
                ('booklocationid', models.AutoField(db_column='BookLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metalocation')),
            ],
            options={
                'db_table': 'BookLocation',
            },
        ),
    ]
