# Generated by Django 4.2.4 on 2024-04-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0115_charactermeta_characterborn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='oldurl2',
        ),
        migrations.AddField(
            model_name='movie',
            name='Change',
            field=models.CharField(db_column='Change', max_length=255, null=True),
        ),
    ]
