# Generated by Django 4.2.4 on 2024-04-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0116_remove_movie_oldurl2_movie_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Change',
        ),
        migrations.AddField(
            model_name='movie',
            name='ChangeURL',
            field=models.CharField(db_column='ChangeURL', max_length=255, null=True),
        ),
    ]
