# Generated by Django 5.1 on 2024-12-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0116_booklocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrating',
            name='bookid',
        ),
        migrations.DeleteModel(
            name='Bookpurchase',
        ),
        migrations.DeleteModel(
            name='Bookrating',
        ),
    ]
