# Generated by Django 5.1 on 2024-12-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0117_remove_bookrating_bookid_delete_bookpurchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookpurchase',
            fields=[
                ('purchaseid', models.AutoField(db_column='PurchaseID', primary_key=True, serialize=False)),
                ('purchasedate', models.DateField(db_column='PurchaseDate')),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
            ],
            options={
                'db_table': 'BookPurchase',
            },
        ),
        migrations.CreateModel(
            name='Bookrating',
            fields=[
                ('ratingid', models.AutoField(db_column='RatingID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(db_column='Comment')),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
            ],
            options={
                'db_table': 'BookRating',
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
