# Generated by Django 4.2.4 on 2024-04-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0118_tvcrew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvepisode',
            name='seasonid',
            field=models.ForeignKey(blank=True, db_column='SeasonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvseason'),
        ),
    ]
