# Generated by Django 5.1 on 2024-12-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0118_bookpurchase_bookrating_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('comment_date', models.DateField(db_column='CommentDate')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
