# Generated by Django 4.2.4 on 2024-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0119_alter_tvepisode_seasonid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imgposter',
            field=models.CharField(db_column='IMGposter', default='noimg.png', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.CharField(db_column='IMG', default='noimg.png', max_length=255),
        ),
    ]
