# Generated by Django 5.1 on 2024-12-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0119_comments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foodmedia',
            name='foodid',
        ),
        migrations.DeleteModel(
            name='Drinkmedia',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Foodmedia',
        ),
    ]
