# Generated by Django 4.2.4 on 2024-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0120_movie_imgposter_alter_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img500x500',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(blank=True, db_column='IMG', max_length=32, null=True),
        ),
    ]
