# Generated by Django 4.2.4 on 2024-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0121_remove_article_img500x500_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseason',
            name='seassonimg',
        ),
        migrations.AddField(
            model_name='tvseason',
            name='img',
            field=models.CharField(blank=True, db_column='IMG', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='imgposter',
            field=models.CharField(blank=True, db_column='IMGposter', max_length=255, null=True),
        ),
    ]
