# Generated by Django 5.1 on 2024-12-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0121_favorite_delete_drink_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drinkid', models.AutoField(db_column='DrinkID', primary_key=True, serialize=False)),
                ('drinkname', models.CharField(db_column='DrinkName', max_length=255)),
                ('drinkurl', models.CharField(blank=True, db_column='DrinkURL', max_length=255, null=True, unique=True)),
                ('description', models.TextField(db_column='Description')),
                ('drinktype', models.CharField(blank=True, db_column='DrinkType', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Drink',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.AutoField(db_column='FoodID', primary_key=True, serialize=False)),
                ('foodname', models.CharField(db_column='FoodName', max_length=255)),
                ('foodurl', models.CharField(blank=True, db_column='FoodURL', max_length=255, null=True, unique=True)),
                ('description', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
    ]
