# Generated by Django 4.2.4 on 2024-04-25 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0122_remove_tvseason_seassonimg_tvseason_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characterbiography',
            fields=[
                ('biographyid', models.AutoField(primary_key=True, serialize=False)),
                ('biographytext', models.TextField(blank=True, db_column='BiographyText', null=True)),
                ('source', models.CharField(blank=True, db_column='Source', max_length=255)),
                ('lastupdated', models.DateField(auto_now=True, db_column='LastUpdated')),
                ('language', models.CharField(db_column='Language', default='en', max_length=10)),
                ('shortdescription', models.TextField(blank=True, db_column='ShortDescription')),
                ('externallink', models.URLField(blank=True, db_column='ExternalLink')),
                ('img', models.URLField(blank=True, db_column='IMG')),
                ('notes', models.TextField(blank=True, db_column='Notes')),
                ('author', models.CharField(blank=True, db_column='Author', max_length=255)),
                ('verificationstatus', models.CharField(choices=[('Verified', 'Verified'), ('Unverified', 'Unverified'), ('Pending', 'Pending')], db_column='VerificationStatus', default='Unverified', max_length=10)),
                ('is_primary', models.BooleanField(db_column='IsPrimary', default=False)),
                ('characterid', models.ForeignKey(db_column='CharacterID', on_delete=django.db.models.deletion.CASCADE, related_name='biographies', to='div_content.charactermeta')),
                ('userid', models.ForeignKey(db_column='UserID', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CharacterBiography',
            },
        ),
    ]
