# Generated by Django 5.1 on 2024-12-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0122_drink_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinkmedia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(db_column='MediaType')),
                ('drinkid', models.ForeignKey(db_column='DrinkID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.drink')),
            ],
            options={
                'db_table': 'DrinkMedia',
            },
        ),
        migrations.CreateModel(
            name='Foodmedia',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(db_column='MediaType')),
                ('foodid', models.ForeignKey(db_column='FoodID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.food')),
            ],
            options={
                'db_table': 'FoodMedia',
            },
        ),
    ]
