# Generated by Django 5.1 on 2024-12-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0123_drinkmedia_foodmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedevelopers',
            name='developerid',
        ),
        migrations.RemoveField(
            model_name='gamedevelopers',
            name='gameid',
        ),
        migrations.DeleteModel(
            name='Gamecomments',
        ),
        migrations.DeleteModel(
            name='Gamedevelopers',
        ),
    ]
