# Generated by Django 4.2.4 on 2024-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0123_characterbiography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermeta',
            name='characterurl',
            field=models.URLField(blank=True, db_column='CharacterURL', max_length=255, null=True, unique=True),
        ),
    ]
