# Generated by Django 5.1 on 2024-12-01 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0124_remove_gamedevelopers_developerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamecomments',
            fields=[
                ('commentid', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameComments',
            },
        ),
        migrations.CreateModel(
            name='Gamedevelopers',
            fields=[
                ('gamedeveloperid', models.AutoField(db_column='GameDeveloperID', primary_key=True, serialize=False)),
                ('developerid', models.ForeignKey(db_column='DeveloperID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metadeveloper')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameDevelopers',
            },
        ),
    ]
