# Generated by Django 4.2.4 on 2024-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0124_alter_charactermeta_characterurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactermeta',
            name='characterborn',
        ),
        migrations.RemoveField(
            model_name='charactermeta',
            name='characterdeath',
        ),
        migrations.RemoveField(
            model_name='charactermeta',
            name='characterdescription',
        ),
        migrations.AddField(
            model_name='characterbiography',
            name='characterborn',
            field=models.CharField(db_column='CharacterBorn', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='characterbiography',
            name='characterdeath',
            field=models.CharField(db_column='CharacterDeath', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='charactermeta',
            name='characterbio',
            field=models.CharField(blank=True, db_column='CharacterBio', max_length=1, null=True),
        ),
    ]
