# Generated by Django 5.1 on 2024-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0125_gamecomments_gamedevelopers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gamedevelopers',
        ),
    ]
