# Generated by Django 4.2.4 on 2024-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0125_remove_charactermeta_characterborn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacollection',
            name='img',
            field=models.CharField(blank=True, db_column='IMG', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='metacollection',
            name='imgposter',
            field=models.CharField(blank=True, db_column='IMGposter', max_length=64, null=True),
        ),
    ]
