# Generated by Django 5.1 on 2024-12-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0126_delete_gamedevelopers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamedevelopers',
            fields=[
                ('gamedeveloperid', models.AutoField(db_column='GameDeveloperID', primary_key=True, serialize=False)),
                ('developerid', models.ForeignKey(db_column='DeveloperID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metadeveloper')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameDevelopers',
            },
        ),
    ]
