# Generated by Django 4.2.4 on 2024-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0126_metacollection_img_metacollection_imgposter'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['url'], name='url_idx'),
        ),
    ]
