# Generated by Django 4.2.4 on 2024-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0127_creator_url_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.TextField(blank=True, db_column='Menu', null=True),
        ),
    ]
