# Generated by Django 5.1 on 2024-12-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0127_gamedevelopers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgame',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='itemgame',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='itemmovie',
            name='itemid',
        ),
        migrations.RemoveField(
            model_name='itemmovie',
            name='movieid',
        ),
        migrations.DeleteModel(
            name='Itembook',
        ),
        migrations.DeleteModel(
            name='Itemgame',
        ),
        migrations.DeleteModel(
            name='Itemmovie',
        ),
    ]
