# Generated by Django 4.2.4 on 2024-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0128_article_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gpsx',
            field=models.CharField(blank=True, db_column='gpsX', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='gpsy',
            field=models.CharField(blank=True, db_column='gpsY', max_length=32, null=True),
        ),
    ]
