# Generated by Django 4.2.4 on 2024-04-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0129_location_gpsx_location_gpsy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AATask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('assigned', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Ke zpracování', 'Ke zpracování'), ('Probíhá', 'Probíhá'), ('Hotovo', 'Hotovo')], db_column='Status', default='Ke zpracování', max_length=16)),
                ('priority', models.CharField(choices=[('Vysoká', 'Vysoká'), ('Střední', 'Střední'), ('Nízká', 'Nízká')], db_column='Priority', default='Střední', max_length=16)),
                ('category', models.CharField(max_length=100)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subtasks', to='div_content.aatask')),
            ],
            options={
                'db_table': 'AATasks',
            },
        ),
    ]
