# Generated by Django 5.1 on 2024-12-01 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0129_delete_itemmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
