# Generated by Django 5.1 on 2024-12-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0131_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemmedia',
            fields=[
                ('mediaitemid', models.AutoField(db_column='MediaItemID', primary_key=True, serialize=False)),
                ('mediatype', models.IntegerField(choices=[('1', 'Book'), ('2', 'Game'), ('3', 'Movie')], db_column='MediaType')),
                ('role', models.IntegerField(choices=[('1', 'Main'), ('2', 'Side'), ('3', 'Prop')], db_column='Role')),
                ('mediaid', models.IntegerField(db_column='MediaID')),
                ('item', models.ForeignKey(db_column='Item', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemMedia',
            },
        ),
    ]
