# Generated by Django 5.1 on 2024-12-01 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0132_itemmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itembook',
            fields=[
                ('bookitemid', models.AutoField(db_column='BookItemID', primary_key=True, serialize=False)),
                ('itemrole', models.CharField(db_column='ItemRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemBook',
            },
        ),
        migrations.CreateModel(
            name='Itemgame',
            fields=[
                ('gameitemid', models.AutoField(db_column='GameItemID', primary_key=True, serialize=False)),
                ('itemrole', models.CharField(db_column='ItemRole', max_length=255)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
            ],
            options={
                'db_table': 'ItemGame',
            },
        ),
        migrations.CreateModel(
            name='Itemmovie',
            fields=[
                ('movieitemid', models.AutoField(db_column='MovieItemID', primary_key=True, serialize=False)),
                ('itemrole', models.IntegerField(db_column='ItemRole')),
                ('itemid', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.item')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'ItemMovie',
            },
        ),
    ]
