# Generated by Django 4.2.4 on 2024-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0132_rename_ipadress_aatask_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='IPaddress',
            field=models.CharField(blank=True, db_column='IPaddress', max_length=64, null=True),
        ),
    ]
