# Generated by Django 5.1 on 2024-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0133_itembook_itemgame_itemmovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metagenre',
            fields=[
                ('genreid', models.AutoField(db_column='GenreID', primary_key=True, serialize=False)),
                ('genrename', models.CharField(db_column='GenreName', max_length=255)),
                ('genrenamecz', models.CharField(db_column='GenreNameCZ', max_length=255)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True, unique=True)),
                ('tmdbid', models.IntegerField(blank=True, db_column='TmdbID', null=True)),
            ],
            options={
                'db_table': 'MetaGenre',
            },
        ),
    ]
