# Generated by Django 4.2.4 on 2024-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0133_alter_aatask_ipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='assigned',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
