# Generated by Django 5.1 on 2024-12-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0134_metagenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookgenre',
            fields=[
                ('bookgenreid', models.AutoField(db_column='BookGenreID', primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
            ],
            options={
                'db_table': 'BookGenre',
            },
        ),
        migrations.CreateModel(
            name='Gamegenre',
            fields=[
                ('gamegenreid', models.AutoField(db_column='GameGenreID', primary_key=True, serialize=False)),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('movieid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
            ],
            options={
                'db_table': 'GameGenre',
            },
        ),
    ]
