# Generated by Django 5.1 on 2024-12-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0135_bookgenre_gamegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gameplatform',
        ),
    ]
