# Generated by Django 4.2.4 on 2024-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0135_remove_aatask_due_date_remove_aatask_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='img',
            field=models.CharField(blank=True, db_column='IMG', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='imgposter',
            field=models.CharField(blank=True, db_column='IMGposter', max_length=64, null=True),
        ),
    ]
