# Generated by Django 5.1 on 2024-12-01 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0136_delete_gameplatform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metaplatform',
        ),
    ]
