# Generated by Django 4.2.4 on 2024-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0136_alter_tvshow_img_alter_tvshow_imgposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testování', 'Testování'), ('Databáze', 'Databáze'), ('Server', 'Server'), ('iOS', 'iOS')], db_column='Category', default='Frontend', max_length=16),
        ),
    ]
