# Generated by Django 4.2.4 on 2024-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0137_alter_aatask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aatask',
            name='Creator',
            field=models.CharField(blank=True, db_column='Creator', max_length=64, null=True),
        ),
    ]
