# Generated by Django 4.2.4 on 2024-05-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0138_aatask_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='status',
            field=models.CharField(choices=[('Ke zpracování', 'Ke zpracování'), ('Probíhá', 'Probíhá'), ('Hotovo', 'Hotovo'), ('Nice to have', 'Nice to have')], db_column='Status', default='Ke zpracování', max_length=16),
        ),
    ]
