# Generated by Django 5.1 on 2024-12-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0139_gameplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatype',
            name='typeid',
            field=models.AutoField(db_column='TypeID', primary_key=True, serialize=False),
        ),
    ]
