# Generated by Django 4.2.4 on 2024-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0140_remove_creatorinmovie_creatorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaindex',
            name='author',
            field=models.CharField(blank=True, db_column='Author', max_length=255, null=True),
        ),
    ]
