# Generated by Django 5.1 on 2024-12-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0140_alter_metatype_typeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviegenre',
            fields=[
                ('moviegenreid', models.AutoField(db_column='MovieGenreID', primary_key=True, serialize=False)),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieGenre',
            },
        ),
        migrations.CreateModel(
            name='Moviecountries',
            fields=[
                ('moviecountriesid', models.AutoField(db_column='MovieCountriesID', primary_key=True, serialize=False, unique=True)),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieCountries',
                'unique_together': {('movieid', 'countryid')},
            },
        ),
    ]
