# Generated by Django 5.1 on 2024-12-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0141_moviegenre_moviecountries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movieversions',
            fields=[
                ('movieversionid', models.AutoField(db_column='MovieVersionID', primary_key=True, serialize=False)),
                ('versionname', models.CharField(db_column='VersionName', max_length=255)),
                ('duration', models.IntegerField(db_column='Duration')),
                ('releasedate', models.DateField(db_column='ReleaseDate')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieVersions',
            },
        ),
    ]
