# Generated by Django 4.2.4 on 2024-05-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0141_metaindex_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaindex',
            name='year',
            field=models.CharField(blank=True, db_column='Year', max_length=255, null=True),
        ),
    ]
