# Generated by Django 4.2.4 on 2024-05-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0142_metaindex_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookwriters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.bookauthor')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.book')),
            ],
            options={
                'db_table': 'BookWriters',
                'unique_together': {('book', 'author')},
            },
        ),
    ]
