# Generated by Django 5.1 on 2024-12-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0142_movieversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvgenre',
            fields=[
                ('tvgenreid', models.AutoField(db_column='TVGenreID', primary_key=True, serialize=False, unique=True)),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metagenre')),
                ('tvshowid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
            ],
            options={
                'db_table': 'TVGenre',
            },
        ),
    ]
