# Generated by Django 4.2.4 on 2024-05-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0143_bookwriters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Metalocation',
        ),
        migrations.RemoveField(
            model_name='locationgame',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='locationgame',
            name='locationid',
        ),
        migrations.RemoveField(
            model_name='locationmovie',
            name='locationid',
        ),
        migrations.RemoveField(
            model_name='locationmovie',
            name='movieid',
        ),
        migrations.AlterModelTable(
            name='metalocation',
            table='MetaLocation',
        ),
        migrations.DeleteModel(
            name='Locationbook',
        ),
        migrations.DeleteModel(
            name='Locationgame',
        ),
        migrations.DeleteModel(
            name='Locationmovie',
        ),
    ]
