# Generated by Django 4.2.4 on 2024-05-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0144_rename_location_metalocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movielocation',
            fields=[
                ('movielocationid', models.IntegerField(db_column='MovieLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('locationid', models.ForeignKey(db_column='LocationID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metalocation')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieLocation',
            },
        ),
    ]
