# Generated by Django 5.1 on 2024-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0144_gamecomments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='url',
            field=models.CharField(blank=True, db_column='URL', max_length=255, null=True, unique=True),
        ),
    ]
