# Generated by Django 5.1 on 2024-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0145_alter_tvshow_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquotes',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
    ]
