# Generated by Django 4.2.4 on 2024-05-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0145_movielocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielocation',
            name='locationid',
            field=models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metalocation'),
        ),
        migrations.CreateModel(
            name='Gamelocation',
            fields=[
                ('gamelocationid', models.IntegerField(db_column='GameLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.game')),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metalocation')),
            ],
            options={
                'db_table': 'GameLocation',
            },
        ),
        migrations.CreateModel(
            name='Booklocation',
            fields=[
                ('booklocationid', models.IntegerField(db_column='BookLocationID', primary_key=True, serialize=False)),
                ('locationrole', models.CharField(db_column='LocationRole', max_length=255)),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.book')),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metalocation')),
            ],
            options={
                'db_table': 'BookLocation',
            },
        ),
    ]
