# Generated by Django 5.1 on 2024-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0146_bookquotes_divrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='creator',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='drink',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='food',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='game',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='item',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='metakeywords',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='metalocation',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='metauniversum',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='movie',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='moviequotes',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='movietrivia',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default='0'),
        ),
    ]
