# Generated by Django 4.2.4 on 2024-05-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0147_metatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatype',
            name='typenamecz',
            field=models.CharField(blank=True, db_column='TypeNameCZ', max_length=255, null=True),
        ),
    ]
