# Generated by Django 5.1 on 2024-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0147_book_divrating_bookauthor_divrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='adult',
            field=models.IntegerField(db_column='Adult', default='0'),
        ),
    ]
