# Generated by Django 5.1 on 2024-12-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0148_creator_adult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesession',
            fields=[
                ('sessionid', models.AutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('chapter', models.CharField(blank=True, db_column='Chapter', max_length=255, null=True)),
                ('season', models.CharField(blank=True, db_column='Season', max_length=255, null=True)),
                ('sessionname', models.CharField(blank=True, db_column='SessionName', max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('backgroundimage', models.CharField(blank=True, db_column='BackgroundImage', max_length=255, null=True)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='div_content.game')),
            ],
            options={
                'db_table': 'GameSession',
            },
        ),
    ]
