# Generated by Django 4.2.4 on 2024-05-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0148_metatype_typenamecz'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalocation',
            name='locationtypeid',
            field=models.ForeignKey(blank=True, db_column='TypeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metatype'),
        ),
    ]
