# Generated by Django 4.2.4 on 2024-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0149_metalocation_locationtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalocation',
            name='locationnamecz',
            field=models.CharField(blank=True, db_column='LocationNameCZ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metalocation',
            name='locationurl',
            field=models.CharField(blank=True, db_column='LocationURL', max_length=255, null=True),
        ),
    ]
