# Generated by Django 5.1 on 2024-12-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0149_gamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameitem',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ItemName', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('itemimage', models.CharField(blank=True, db_column='ItemImage', max_length=255, null=True)),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='div_content.gamelocation')),
                ('sessionid', models.ForeignKey(blank=True, db_column='SessionID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='div_content.gamesession')),
            ],
            options={
                'db_table': 'GameItem',
            },
        ),
    ]
