# Generated by Django 4.2.4 on 2024-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0150_metalocation_locationnamecz_metalocation_locationurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalocation',
            name='locationurl',
            field=models.CharField(db_column='LocationURL', max_length=255, unique=True),
        ),
    ]
