# Generated by Django 5.1 on 2024-12-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0150_gameitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameseason',
            fields=[
                ('seasonid', models.AutoField(db_column='SeasonID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SeasonName', max_length=255)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='games/seasons/')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='seasons', to='div_content.game')),
            ],
            options={
                'db_table': 'GameSeason',
            },
        ),
    ]
