# Generated by Django 5.1 on 2024-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0151_gameseason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameseason',
            old_name='name',
            new_name='seasonname',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='chapter',
        ),
        migrations.AddField(
            model_name='gameseason',
            name='chapter',
            field=models.CharField(blank=True, db_column='Chapter', max_length=255, null=True),
        ),
    ]
