# Generated by Django 4.2.4 on 2024-05-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0151_alter_metalocation_locationurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='metacity',
            name='namecitycz',
            field=models.CharField(blank=True, db_column='NameCityCZ', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Metastreet',
            fields=[
                ('StreetID', models.AutoField(db_column='StreetID', primary_key=True, serialize=False)),
                ('StreetName', models.CharField(db_column='StreetName', max_length=255)),
                ('StreetNameCZ', models.CharField(blank=True, db_column='StreetNameCZ', max_length=255, null=True)),
                ('StreetNameURL', models.CharField(blank=True, db_column='StreetNameURL', max_length=255, null=True)),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.metacity')),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
            ],
            options={
                'db_table': 'MetaStreet',
            },
        ),
    ]
