# Generated by Django 5.1 on 2024-12-10 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0152_rename_name_gameseason_seasonname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameseason',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='season',
        ),
        migrations.AddField(
            model_name='gameseason',
            name='backgroundimage',
            field=models.CharField(blank=True, db_column='BackgroundImage', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='chapter',
            field=models.CharField(blank=True, db_column='Chapter', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='seasonid',
            field=models.ForeignKey(blank=True, db_column='SeasonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='div_content.gameseason'),
        ),
    ]
