# Generated by Django 5.1 on 2024-12-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0153_remove_gameseason_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelocation',
            name='locationname',
            field=models.CharField(blank=True, db_column='LocationName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamelocation',
            name='relatedseason',
            field=models.ForeignKey(blank=True, db_column='RelatedSeason', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='div_content.gameseason'),
        ),
    ]
