# Generated by Django 4.2.4 on 2024-05-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0153_alter_metacity_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='universumid',
            field=models.ForeignKey(blank=True, db_column='UniversumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metauniversum'),
        ),
    ]
