# Generated by Django 4.2.4 on 2024-05-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0154_alter_book_universumid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookwriters',
            name='author',
            field=models.ForeignKey(db_column='AuthorID', on_delete=django.db.models.deletion.CASCADE, to='div_content.bookauthor'),
        ),
        migrations.AlterField(
            model_name='bookwriters',
            name='book',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book'),
        ),
    ]
