# Generated by Django 5.1 on 2024-12-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0154_gamelocation_locationname_gamelocation_relatedseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='gameid',
            field=models.ForeignKey(blank=True, db_column='GameID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='div_content.game'),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='seasonid',
            field=models.ForeignKey(blank=True, db_column='SeasonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='div_content.gameseason'),
        ),
    ]
