# Generated by Django 5.1 on 2024-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0155_gameitem_gameid_gameitem_seasonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='divrating',
            field=models.IntegerField(db_column='DIVRating', db_index=True, default=0),
        ),
    ]
