# Generated by Django 4.2.4 on 2024-05-22 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0155_alter_bookwriters_author_alter_bookwriters_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='universumid',
            field=models.ForeignKey(db_column='UniversumID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metauniversum'),
        ),
        migrations.DeleteModel(
            name='Bookwriters',
        ),
    ]
