# Generated by Django 5.1 on 2024-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0156_alter_game_divrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelocation',
            name='shortdescription',
            field=models.CharField(blank=True, db_column='ShortDescription', max_length=255, null=True),
        ),
    ]
