# Generated by Django 5.1 on 2024-12-10 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0157_gamelocation_shortdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamespecial',
            fields=[
                ('specialid', models.AutoField(db_column='SpecialID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='SpecialName', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('gametype', models.CharField(db_column='GameType', max_length=50)),
                ('image', models.CharField(blank=True, db_column='Image', max_length=255, null=True)),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='specials', to='div_content.game')),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specials', to='div_content.gamelocation')),
            ],
            options={
                'db_table': 'GameSpecial',
            },
        ),
        migrations.CreateModel(
            name='Gametask',
            fields=[
                ('taskid', models.AutoField(db_column='TaskID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='TaskName', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('target_quantity', models.IntegerField(db_column='TargetQuantity')),
                ('gameid', models.ForeignKey(db_column='GameID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='div_content.game')),
                ('seasonid', models.ForeignKey(blank=True, db_column='SeasonID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='div_content.gameseason')),
                ('sessionid', models.ForeignKey(blank=True, db_column='SessionID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='div_content.gamesession')),
            ],
            options={
                'db_table': 'GameTask',
            },
        ),
        migrations.CreateModel(
            name='Taskitem',
            fields=[
                ('taskitemid', models.AutoField(db_column='TaskItemID', primary_key=True, serialize=False)),
                ('hint', models.TextField(blank=True, db_column='Hint', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('itemimage', models.CharField(blank=True, db_column='ItemImage', max_length=255, null=True)),
                ('locationid', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_items', to='div_content.gamelocation')),
                ('taskid', models.ForeignKey(db_column='TaskID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='div_content.gametask')),
            ],
            options={
                'db_table': 'TaskItem',
            },
        ),
    ]
