# Generated by Django 4.2.4 on 2024-05-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0157_bookwriters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characterbook',
            new_name='Charactercharacter',
        ),
        migrations.AlterModelTable(
            name='charactercharacter',
            table='BookCharacter',
        ),
    ]
