# Generated by Django 5.1 on 2024-12-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0158_gamespecial_gametask_taskitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taskitem',
            new_name='Gametaskitem',
        ),
        migrations.AlterModelTable(
            name='gametaskitem',
            table='GameTaskItem',
        ),
    ]
