# Generated by Django 4.2.4 on 2024-05-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0159_alter_book_title_alter_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookisbn',
            name='book',
            field=models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book'),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='coverimage',
            field=models.URLField(blank=True, db_column='CoverIMG', null=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='description',
            field=models.TextField(blank=True, db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='edition',
            field=models.CharField(blank=True, db_column='Edition', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='format',
            field=models.CharField(blank=True, db_column='Format', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='isbn',
            field=models.CharField(db_column='ISBN', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookisbn',
            name='publicationyear',
            field=models.IntegerField(blank=True, db_column='PublicationYear', null=True),
        ),
    ]
