# Generated by Django 5.1 on 2024-12-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('div_content', '0159_rename_taskitem_gametaskitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSum',
            fields=[
                ('favorite_sum_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'FavoriteSum',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
