# Generated by Django 4.2.4 on 2024-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0160_alter_bookisbn_book_alter_bookisbn_coverimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genreid',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=2, null=True),
        ),
    ]
