# Generated by Django 5.1 on 2024-12-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0160_favoritesum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='bookquotes',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='metakeywords',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='metalocation',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='metauniversum',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='moviequotes',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='movietrivia',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='divrating',
            field=models.IntegerField(blank=True, db_column='DIVRating', db_index=True, default='0', null=True),
        ),
    ]
