# Generated by Django 5.1 on 2024-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0161_alter_book_divrating_alter_bookauthor_divrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='special',
            field=models.IntegerField(blank=True, db_column='Special', db_index=True, null=True),
        ),
    ]
