# Generated by Django 4.2.4 on 2024-05-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0162_bookgenre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charactercharacter',
            new_name='Bookcharacter',
        ),
    ]
