# Generated by Django 5.1 on 2024-12-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0162_alter_movie_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='special',
            field=models.IntegerField(blank=True, db_column='Special', db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='special',
            field=models.IntegerField(blank=True, db_column='Special', db_index=True, null=True),
        ),
    ]
