# Generated by Django 4.2.4 on 2024-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0163_rename_charactercharacter_bookcharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcharacter',
            name='characterrole',
        ),
        migrations.AddField(
            model_name='bookcharacter',
            name='charactermain',
            field=models.CharField(blank=True, db_column='CharacterMain', max_length=2, null=True),
        ),
    ]
