# Generated by Django 4.2.4 on 2024-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0164_remove_bookcharacter_characterrole_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcharacter',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookcharacter',
            name='bookcharacterid',
            field=models.IntegerField(db_column='BookCharacterID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
