# Generated by Django 5.1 on 2024-12-14 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0164_tvseason_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvshowcomments',
            fields=[
                ('commentid', models.AutoField(db_column='CommentID', primary_key=True, serialize=False)),
                ('comment', models.TextField(db_column='Comment')),
                ('dateadded', models.DateTimeField(auto_now_add=True, db_column='DateAdded')),
                ('tvshowkid', models.ForeignKey(db_column='TVShowID', on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.tvshow')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TVShowComments',
            },
        ),
    ]
