# Generated by Django 4.2.4 on 2024-05-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0165_remove_bookcharacter_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookgenre',
            old_name='movieid',
            new_name='bookid',
        ),
    ]
