# Generated by Django 5.1 on 2024-12-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0165_tvshowcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermeta',
            name='charactername',
            field=models.CharField(blank=True, db_column='CharacterName', db_index=True, max_length=255, null=True),
        ),
    ]
