# Generated by Django 4.2.4 on 2024-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0166_rename_movieid_bookgenre_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lastupdated',
            field=models.DateField(auto_now=True, db_column='LastUpdated'),
        ),
    ]
