# Generated by Django 5.1 on 2024-12-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('div_content', '0166_alter_charactermeta_charactername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlistitem',
            fields=[
                ('userlistitemid', models.AutoField(db_column='UserListItemID', primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(db_column='ObjectID')),
                ('addedat', models.DateTimeField(auto_now_add=True, db_column='AddedAt')),
                ('content_type', models.ForeignKey(db_column='ContentTypeID', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('userlist', models.ForeignKey(db_column='UserListID', on_delete=django.db.models.deletion.CASCADE, to='div_content.userlist')),
            ],
            options={
                'db_table': 'UserListItem',
                'unique_together': {('userlist', 'content_type', 'object_id')},
            },
        ),
    ]
