# Generated by Django 5.1 on 2024-12-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0167_userlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movietranslation',
            fields=[
                ('movietranslationid', models.AutoField(db_column='MovieTranslationID', primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=5, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('movie', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieTranslation',
            },
        ),
    ]
