# Generated by Django 4.2.4 on 2024-06-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0168_alter_bookisbn_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookisbn',
            name='edition',
        ),
        migrations.AddField(
            model_name='bookisbn',
            name='ISBNtype',
            field=models.CharField(blank=True, db_column='ISBNtype', max_length=255, null=True),
        ),
    ]
