# Generated by Django 5.1 on 2024-12-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0168_movietranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='descriptioncz',
            field=models.TextField(blank=True, db_column='DescriptionCZ', null=True),
        ),
    ]
