# Generated by Django 5.1 on 2024-12-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0169_game_descriptioncz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamegenre',
            old_name='movieid',
            new_name='gameid',
        ),
    ]
