# Generated by Django 4.2.4 on 2024-06-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0169_remove_bookisbn_edition_bookisbn_isbntype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metasoundtrack',
            fields=[
                ('soundtrackid', models.AutoField(db_column='SoundtrackID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('albumname', models.CharField(blank=True, db_column='AlbumName', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('release_date', models.DateField(blank=True, db_column='ReleaseDate', null=True)),
                ('img', models.CharField(db_column='IMG', default='n.png', max_length=255)),
                ('parentid', models.ForeignKey(blank=True, db_column='ParentID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.metasoundtrack')),
            ],
            options={
                'db_table': 'MetaSoundtrack',
            },
        ),
        migrations.CreateModel(
            name='Movietrailer',
            fields=[
                ('trailerid', models.AutoField(db_column='TrailerID', primary_key=True, serialize=False)),
                ('youtubeurl', models.URLField(db_column='YoutubeURL')),
                ('duration', models.DurationField(blank=True, db_column='Duration', null=True)),
                ('date_added', models.DateField(auto_now_add=True, db_column='DateAdded')),
                ('views', models.IntegerField(db_column='Views', default=0)),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieTrailer',
            },
        ),
        migrations.CreateModel(
            name='Moviesoundtrack',
            fields=[
                ('msid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
                ('soundtrack', models.ForeignKey(db_column='SoundtrackID', on_delete=django.db.models.deletion.CASCADE, to='div_content.metasoundtrack')),
            ],
            options={
                'db_table': 'MovieSoundtrack',
            },
        ),
        migrations.CreateModel(
            name='MovieQuotes',
            fields=[
                ('quoteid', models.AutoField(db_column='QuoteID', primary_key=True, serialize=False)),
                ('quote', models.TextField(db_column='Quote')),
                ('actor', models.ForeignKey(blank=True, db_column='ActorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.creator')),
                ('character', models.ForeignKey(blank=True, db_column='CharacterID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.charactermeta')),
                ('movie', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
                ('parentquote', models.ForeignKey(blank=True, db_column='ParentQuoteID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.moviequotes')),
            ],
            options={
                'db_table': 'MovieQuotes',
            },
        ),
        migrations.CreateModel(
            name='Movieproduction',
            fields=[
                ('productionid', models.AutoField(db_column='ProductionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('headquarters', models.CharField(blank=True, db_column='Headquarters', max_length=255, null=True)),
                ('homepage', models.URLField(blank=True, db_column='Homepage', null=True)),
                ('logopath', models.CharField(db_column='LogoPath', default='n.png', max_length=255)),
                ('origincountry', models.CharField(blank=True, db_column='OriginCountry', max_length=4, null=True)),
                ('countryid', models.ForeignKey(blank=True, db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
                ('parentcompanyid', models.ForeignKey(blank=True, db_column='ParentCompanyID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.movieproduction')),
            ],
            options={
                'db_table': 'MovieProduction',
            },
        ),
        migrations.CreateModel(
            name='Moviedistributor',
            fields=[
                ('distributorid', models.AutoField(db_column='DistributorID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('countryid', models.ForeignKey(db_column='CountryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='div_content.metacountry')),
            ],
            options={
                'db_table': 'MovieDistributor',
            },
        ),
        migrations.CreateModel(
            name='Moviecinema',
            fields=[
                ('mcid', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('releasedate', models.DateField(blank=True, db_column='ReleaseDate', null=True)),
                ('distributorid', models.ForeignKey(blank=True, db_column='DistributorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.moviedistributor')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
            ],
            options={
                'db_table': 'MovieCinema',
            },
        ),
        migrations.CreateModel(
            name='BookQuotes',
            fields=[
                ('quoteid', models.AutoField(db_column='QuoteID', primary_key=True, serialize=False)),
                ('quote', models.TextField(db_column='Quote')),
                ('authorid', models.ForeignKey(blank=True, db_column='AuthorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.bookauthor')),
                ('bookid', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='div_content.book')),
                ('characterid', models.ForeignKey(blank=True, db_column='CharacterID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.charactermeta')),
                ('parentquoteid', models.ForeignKey(blank=True, db_column='ParentQuoteID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.bookquotes')),
            ],
            options={
                'db_table': 'BookQuotes',
            },
        ),
    ]
