# Generated by Django 5.1 on 2024-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0170_rename_movieid_gamegenre_gameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='systemrequirements',
            field=models.TextField(blank=True, db_column='SystemRequirements', null=True),
        ),
    ]
