# Generated by Django 4.2.4 on 2024-06-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0171_rename_movietrailer_movie_trailer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_trailer',
            new_name='Movietrailer',
        ),
    ]
