# Generated by Django 5.1 on 2024-12-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0171_game_systemrequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='universumid',
        ),
    ]
