# Generated by Django 4.2.4 on 2024-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0174_alter_drink_drinkurl_alter_food_foodurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drinktype',
            field=models.CharField(blank=True, db_column='DrinkType', max_length=255, null=True),
        ),
    ]
