# Generated by Django 5.1 on 2024-12-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0174_remove_tvshow_universumid'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauniversum',
            name='tmdbid',
            field=models.IntegerField(blank=True, db_column='TmdbID', null=True),
        ),
        migrations.AlterField(
            model_name='metauniversum',
            name='universumid',
            field=models.AutoField(db_column='UniversumID', primary_key=True, serialize=False),
        ),
    ]
