# Generated by Django 4.2.4 on 2024-06-16 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0175_drink_drinktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movietrivia',
            fields=[
                ('triviaid', models.AutoField(db_column='TriviaID', primary_key=True, serialize=False)),
                ('trivia', models.TextField(db_column='Trivia')),
                ('creatorid', models.ForeignKey(blank=True, db_column='CreatorID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.creator')),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='div_content.movie')),
                ('parenttriviaid', models.ForeignKey(blank=True, db_column='ParentTriviaID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.movietrivia')),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MovieTrivia',
            },
        ),
    ]
