# Generated by Django 4.2.4 on 2024-06-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0176_movietrivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlisttype',
            fields=[
                ('userlisttypeid', models.AutoField(db_column='UserListTypeID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'UserListType',
            },
        ),
        migrations.AddField(
            model_name='userlist',
            name='listtype',
            field=models.ForeignKey(blank=True, db_column='ListTypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='div_content.userlisttype'),
        ),
    ]
