# Generated by Django 5.1 on 2024-12-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0176_book_universumid_game_universumid_movie_universumid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='titlecz',
            field=models.CharField(blank=True, db_column='TitleCZ', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, db_column='Title', max_length=255, null=True),
        ),
    ]
