# Generated by Django 4.2.4 on 2024-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0177_userlisttype_userlist_listtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='special',
            field=models.IntegerField(blank=True, choices=[('1', 'Top'), ('2', 'CZ')], db_column='Special', db_index=True, null=True),
        ),
    ]
