# Generated by Django 5.1 on 2024-12-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0177_book_titlecz_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lastupdated',
            field=models.DateField(db_column='LastUpdated'),
        ),
    ]
