# Generated by Django 5.1 on 2024-12-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0180_userbookgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='priority',
            field=models.CharField(choices=[('Vysoká', 'Vysoká'), ('Střední', 'Střední'), ('Nízká', 'Nízká'), ('Nice to have', 'Nice to have')], db_column='Priority', default='Střední', max_length=16),
        ),
    ]
