# Generated by Django 5.1 on 2024-12-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0181_alter_aatask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='category',
            field=models.CharField(choices=[('Knihy', 'Knihy'), ('Backend', 'Backend'), ('Testování', 'Testování'), ('Databáze', 'Databáze'), ('Server', 'Server'), ('iOS', 'iOS')], db_column='Category', default='Knihy', max_length=16),
        ),
    ]
