# Generated by Django 5.1 on 2024-12-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0182_alter_aatask_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aatask',
            name='category',
            field=models.CharField(choices=[('Knihy', 'Knihy'), ('Hry', 'Hry'), ('Filmy', 'Filmy'), ('eShop', 'eShop'), ('Server', 'Server'), ('Ostatní', 'Ostatní')], db_column='Category', default='Knihy', max_length=16),
        ),
    ]
