# Generated by Django 5.1 on 2024-12-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0183_alter_aatask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='metauniversum',
            name='universumdescriptioncz',
            field=models.TextField(db_column='UniversumDescriptionCZ', null=True),
        ),
        migrations.AlterField(
            model_name='aatask',
            name='duedate',
            field=models.DateField(blank=True, db_column='DueDate', default='2025-10-10', null=True),
        ),
    ]
