# Generated by Django 4.2.4 on 2024-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0184_movielinks_linkautor_alter_movielinks_linktext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielinks',
            name='linkdescription',
            field=models.CharField(blank=True, db_column='LinkDescription', max_length=5125, null=True),
        ),
        migrations.AlterField(
            model_name='movielinks',
            name='linktext',
            field=models.CharField(blank=True, db_column='LinkText', max_length=255, null=True),
        ),
    ]
