# Generated by Django 5.1 on 2024-12-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0184_metauniversum_universumdescriptioncz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metauniversum',
            name='universumurl',
            field=models.CharField(blank=True, db_column='UniversumURL', max_length=255, null=True, unique=True),
        ),
    ]
