# Generated by Django 4.2.4 on 2024-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0185_alter_movielinks_linkdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermeta',
            name='charactername',
            field=models.CharField(blank=True, db_column='CharacterName', max_length=255, null=True),
        ),
    ]
