# Generated by Django 5.1 on 2024-12-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0186_alter_characterbiography_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbiography',
            name='language',
            field=models.CharField(blank=True, db_column='Language', max_length=10, null=True),
        ),
    ]
