# Generated by Django 5.1 on 2024-12-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0187_alter_characterbiography_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterbiography',
            name='shortdescription',
        ),
        migrations.AddField(
            model_name='characterbiography',
            name='biographytextcz',
            field=models.TextField(blank=True, db_column='BiographyTextCZ', null=True),
        ),
    ]
