# Generated by Django 5.1 on 2024-12-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0188_remove_characterbiography_shortdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorbiography',
            name='shortdescription',
        ),
        migrations.AddField(
            model_name='creatorbiography',
            name='biographytextcz',
            field=models.TextField(blank=True, db_column='BiographyTextCZ'),
        ),
    ]
