# Generated by Django 4.2.4 on 2024-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0192_moviecomments_dateadded_alter_metakeywords_tmdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomments',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, db_column='DateAdded'),
        ),
    ]
