# Generated by Django 4.2.4 on 2024-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0193_alter_moviecomments_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakeywords',
            name='keywordurl',
            field=models.CharField(blank=True, db_column='KeywordURL', max_length=255, null=True),
        ),
    ]
