# Generated by Django 4.2.4 on 2024-08-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0195_articlenews_newsassociation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsAssociation',
            new_name='Articlenewsassociation',
        ),
        migrations.AlterModelTable(
            name='articlenewsassociation',
            table='ArticleNewsAssociation',
        ),
    ]
