# Generated by Django 4.2.4 on 2024-08-27 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0197_alter_articlenews_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forumsection',
            fields=[
                ('forumsectionid', models.AutoField(db_column='ForumSectionID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('slug', models.SlugField(blank=True, db_column='Slug', max_length=255, null=True, unique=True)),
                ('imageurl', models.CharField(blank=True, db_column='ImageURL', help_text='Image URL', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ForumSection',
            },
        ),
        migrations.CreateModel(
            name='Forumtopic',
            fields=[
                ('forumtopicid', models.AutoField(db_column='ForumTopicID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255, unique=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('topicurl', models.SlugField(db_column='URL', max_length=255, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.forumsection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ForumTopic',
            },
        ),
        migrations.CreateModel(
            name='Forumcomment',
            fields=[
                ('forumcommentid', models.AutoField(db_column='ForumCommentID', primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='Created_at')),
                ('lasteditedat', models.DateTimeField(blank=True, db_column='LastEditedAt', null=True)),
                ('parentcommentid', models.IntegerField(blank=True, db_column='ParentCommentID', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='div_content.forumtopic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ForumComment',
            },
        ),
    ]
