# Generated by Django 4.2.4 on 2024-08-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0199_avatar_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatar',
            table='Avatar',
        ),
    ]
