# Generated by Django 4.2.4 on 2024-08-27 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('div_content', '0200_alter_avatar_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articleblog',
            fields=[
                ('articleblogid', models.AutoField(db_column='ArticleBlogID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('slug', models.SlugField(db_column='Slug', max_length=255, unique=True)),
                ('blog_type', models.CharField(choices=[('book', 'Knižní'), ('game', 'Herní'), ('movie', 'Filmový'), ('general', 'Obecný')], db_column='BlogType', default='general', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleBlog',
            },
        ),
        migrations.CreateModel(
            name='Articleblogpost',
            fields=[
                ('articleblogpostid', models.AutoField(db_column='ArticleBlogPostID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('slug', models.SlugField(blank=True, db_column='Slug', max_length=255, null=True, unique=True)),
                ('content', models.TextField(db_column='Content')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=100, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_column='PublishedAt')),
                ('tags', models.CharField(blank=True, db_column='Tags', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('is_public', models.BooleanField(db_column='IsPublic', default=True)),
                ('articleblog', models.ForeignKey(db_column='ArticleBlogID', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='div_content.articleblog')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleBlogPost',
            },
        ),
        migrations.CreateModel(
            name='Userdivcoins',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('totaldivcoins', models.DecimalField(db_column='TotalDivCoins', decimal_places=2, default=0.0, max_digits=10)),
                ('weeklydivcoins', models.DecimalField(db_column='WeeklyDivCoins', decimal_places=2, default=0.0, max_digits=10)),
                ('monthlydivcoins', models.DecimalField(db_column='MonthlyDivCoins', decimal_places=2, default=0.0, max_digits=10)),
                ('yearlydivcoins', models.DecimalField(db_column='YearlyDivCoins', decimal_places=2, default=0.0, max_digits=10)),
                ('lastupdated', models.DateField(auto_now=True, db_column='LastUpdated')),
            ],
            options={
                'db_table': 'UserDivCoins',
            },
        ),
        migrations.CreateModel(
            name='Articleinteraction',
            fields=[
                ('articleinteractionid', models.AutoField(db_column='ArticleInteractionID', primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(db_column='InteractionType', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('articleblogpost', models.ForeignKey(db_column='ArticleBlogPostID', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='div_content.articleblogpost')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleInteraction',
            },
        ),
        migrations.CreateModel(
            name='Articleblogcomment',
            fields=[
                ('articleblogcommentid', models.AutoField(db_column='ArticleBlogCommentID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('articleblogpost', models.ForeignKey(db_column='ArticleBlogPostID', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='div_content.articleblogpost')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleBlogComment',
            },
        ),
    ]
