# Generated by Django 4.2.4 on 2024-08-31 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('div_content', '0202_metastats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquotes',
            name='page_number',
            field=models.IntegerField(blank=True, db_column='PageNumber', null=True),
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
