# Generated by Django 4.2.4 on 2024-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0204_remove_bookquotes_page_number_bookquotes_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookquotes',
            name='thumbsdown',
            field=models.IntegerField(db_column='ThumbsDown', default=0),
        ),
        migrations.AddField(
            model_name='bookquotes',
            name='thumbsup',
            field=models.IntegerField(db_column='ThumbsUp', default=0),
        ),
    ]
