# Generated by Django 4.2.4 on 2024-09-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0206_creator_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='genre',
        ),
        migrations.AddField(
            model_name='creator',
            name='gender',
            field=models.IntegerField(blank=True, db_column='Gender', default=0, null=True),
        ),
    ]
