# Generated by Django 5.1 on 2024-12-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('div_content', '0189_remove_creatorbiography_shortdescription_and_more'),
        ('div_content', '0207_remove_creator_genre_creator_gender'),
    ]

    operations = [
    ]
